# /orquestador-multi-agente/frontend/Dockerfile
FROM node:20-alpine

WORKDIR /app

# No copiamos ni instalamos nada aquí, porque 
# el docker-compose.yml se encargará de todo al arrancar.

EXPOSE 3000