import os

def w(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"✅ Reparación Producción: {path}")

# 1. FIX GITHUB ROUTER (Control de Errores y Auditoría)
w("backend/app/routers/github.py", [
    "import subprocess, httpx, shutil",
    "from uuid import UUID",
    "from fastapi import APIRouter, Depends",
    "from app.database import get_db",
    "from app.config import get_settings",
    "from app.models import Proyecto",
    "from app.models.audit import EventoAuditoria",
    "router = APIRouter()",
    "settings = get_settings()",
    "async def get_cwd(project_id, db):",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    path = settings.base_projects_dir / p.nombre_slug",
    "    path.mkdir(parents=True, exist_ok=True)",
    "    return str(path)",
    "@router.post('/{project_id}/status')",
    "async def git_status(project_id: str, db=Depends(get_db)):",
    "    cwd = await get_cwd(project_id, db)",
    "    subprocess.run(['git', 'init'], cwd=cwd)",
    "    res = subprocess.run(['git', 'status'], cwd=cwd, capture_output=True, text=True)",
    "    return {'output': res.stdout or res.stderr}",
    "@router.post('/{project_id}/add')",
    "async def git_add(project_id: str, db=Depends(get_db)):",
    "    cwd = await get_cwd(project_id, db)",
    "    res = subprocess.run(['git', 'add', '.'], cwd=cwd, capture_output=True, text=True)",
    "    return {'output': 'Archivos agregados.\\n' + (res.stdout or res.stderr)}",
    "@router.post('/{project_id}/commit')",
    "async def git_commit(project_id: str, db=Depends(get_db)):",
    "    cwd = await get_cwd(project_id, db)",
    "    subprocess.run(['git', 'config', 'user.email', 'bot@nodara.local'], cwd=cwd)",
    "    subprocess.run(['git', 'config', 'user.name', 'Nodara Bot'], cwd=cwd)",
    "    res = subprocess.run(['git', 'commit', '-m', 'Commit Automático Nodara'], cwd=cwd, capture_output=True, text=True)",
    "    return {'output': res.stdout or res.stderr}",
    "@router.post('/{project_id}/push')",
    "async def git_push(project_id: str, db=Depends(get_db)):",
    "    cwd = await get_cwd(project_id, db)",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    tk = settings.github_personal_access_token",
    "    if not tk or not p.github_url: return {'output': 'Error: GitOps sin configurar.'}",
    "    repo_name = p.github_url.split('/')[-1].replace('.git', '')",
    "    is_private = p.estado != 'publico'",
    "    try:",
    "        async with httpx.AsyncClient() as client:",
    "            headers = {'Authorization': f'Bearer {tk}', 'Accept': 'application/vnd.github.v3+json', 'User-Agent': 'Nodara-Enterprise'}",
    "            await client.post('https://api.github.com/user/repos', headers=headers, json={'name': repo_name, 'private': is_private, 'description': p.descripcion})",
    "    except Exception as e:",
    "        pass # Ignoramos si ya existe o falla en push manual, intentamos el push igual",
    "    auth = p.github_url.replace('https://', f'https://{tk}@')",
    "    subprocess.run(['git', 'branch', '-M', 'main'], cwd=cwd)",
    "    res = subprocess.run(['git', 'push', auth, 'main'], cwd=cwd, capture_output=True, text=True)",
    "    if res.returncode == 0:",
    "        db.add(EventoAuditoria(actor='Sistema', action='Git Push Manual Exitoso', target=repo_name, severity='success'))",
    "    else:",
    "        db.add(EventoAuditoria(actor='Sistema', action='Git Push Manual Fallido', target=repo_name, severity='danger'))",
    "    await db.commit()",
    "    return {'output': f'Push ejecutado:\\n{res.stdout or res.stderr}'}",
    "@router.delete('/{project_id}/repo')",
    "async def delete_repo(project_id: str, db=Depends(get_db)):",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    tk = settings.github_personal_access_token",
    "    if tk and p.github_url:",
    "        parts = p.github_url.replace('.git', '').split('/')",
    "        if len(parts) >= 4:",
    "            owner, repo = parts[-2], parts[-1]",
    "            try:",
    "                async with httpx.AsyncClient() as client:",
    "                    headers = {'Authorization': f'Bearer {tk}', 'Accept': 'application/vnd.github.v3+json', 'User-Agent': 'Nodara-Enterprise'}",
    "                    r = await client.delete(f'https://api.github.com/repos/{owner}/{repo}', headers=headers)",
    "                    if r.status_code == 204:",
    "                        db.add(EventoAuditoria(actor='GitOps', action='Repo Eliminado en GitHub', target=repo, severity='warning'))",
    "                    elif r.status_code != 404:",
    "                        error_msg = r.json().get('message', 'Error') if r.text else str(r.status_code)",
    "                        db.add(EventoAuditoria(actor='GitOps', action=f'No se pudo borrar Github: {error_msg}', target=repo, severity='danger'))",
    "                    await db.commit()",
    "            except Exception as e:",
    "                db.add(EventoAuditoria(actor='GitOps', action=f'Excepción borrando Github: {str(e)[:50]}', target=repo, severity='danger'))",
    "                await db.commit()",
    "    return {'status': 'ok'}"
])

# 2. FIX PROJECTS ROUTER (Creación segura, Logs estrictos y Push protegido)
w("backend/app/routers/projects.py", [
    "import os, subprocess, base64, mimetypes, shutil, httpx",
    "from uuid import UUID",
    "from pathlib import Path",
    "from fastapi import APIRouter, Depends, HTTPException",
    "from sqlalchemy import select",
    "from sqlalchemy.ext.asyncio import AsyncSession",
    "from pydantic import BaseModel",
    "from app.database import get_db",
    "from app.config import get_settings",
    "from app.schemas import ProyectoCreate, ProyectoOut",
    "from app.services.slug import slugify",
    "from app.models.audit import EventoAuditoria",
    "router = APIRouter()",
    "settings = get_settings()",
    "class ReadmeUpdate(BaseModel): content: str",
    "class FileUpdate(BaseModel): content: str",
    "@router.get('', response_model=list[ProyectoOut])",
    "async def list_projects(db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    res = await db.execute(select(Proyecto).order_by(Proyecto.fecha_creacion.desc()))",
    "    return list(res.scalars().all())",
    "@router.post('', response_model=ProyectoOut)",
    "async def create_project(payload: ProyectoCreate, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    slug = payload.nombre_slug or slugify(payload.titulo)",
    "    data = payload.model_dump()",
    "    valid_keys = Proyecto.__table__.columns.keys()",
    "    filtered_data = {k: v for k, v in data.items() if k in valid_keys and k != 'nombre_slug'}",
    "    obj = Proyecto(**filtered_data, nombre_slug=slug)",
    "    db.add(obj)",
    "    db.add(EventoAuditoria(actor='Sistema', action='Proyecto Registrado en DB', target=slug, severity='success'))",
    "    await db.commit()",
    "    await db.refresh(obj)",
    "    try:",
    "        ws = settings.base_projects_dir / obj.nombre_slug",
    "        ws.mkdir(parents=True, exist_ok=True)",
    "        with open(ws / 'README.md', 'w', encoding='utf-8') as f: ",
    "            f.write('# ' + obj.titulo + '\\n\\n' + obj.descripcion)",
    "        tk = settings.github_personal_access_token",
    "        if tk and obj.github_url:",
    "            repo_name = obj.github_url.split('/')[-1].replace('.git', '')",
    "            is_private = obj.estado != 'publico'",
    "            async with httpx.AsyncClient() as client:",
    "                headers = {'Authorization': f'Bearer {tk}', 'Accept': 'application/vnd.github.v3+json', 'User-Agent': 'Nodara-Enterprise'}",
    "                api_res = await client.post('https://api.github.com/user/repos', headers=headers, json={'name': repo_name, 'private': is_private, 'description': obj.descripcion})",
    "                if api_res.status_code in [200, 201]:",
    "                    db.add(EventoAuditoria(actor='GitOps', action='Repo Creado en GitHub', target=repo_name, severity='success'))",
    "                else:",
    "                    error_msg = api_res.json().get('message', str(api_res.status_code)) if api_res.text else str(api_res.status_code)",
    "                    db.add(EventoAuditoria(actor='GitOps', action=f'GitHub rechazó creación: {error_msg[:100]}', target=repo_name, severity='danger'))",
    "                    await db.commit()",
    "                    return obj # Evita intentar hacer push a un repo que no se creó",
    "            # Setup local Git",
    "            subprocess.run(['git', 'init'], cwd=str(ws))",
    "            subprocess.run(['git', 'add', '.'], cwd=str(ws))",
    "            subprocess.run(['git', 'config', 'user.email', 'bot@nodara.local'], cwd=str(ws))",
    "            subprocess.run(['git', 'config', 'user.name', 'Nodara Bot'], cwd=str(ws))",
    "            subprocess.run(['git', 'commit', '-m', 'Commit Inicial'], cwd=str(ws))",
    "            auth = obj.github_url.replace('https://', f'https://{tk}@')",
    "            subprocess.run(['git', 'branch', '-M', 'main'], cwd=str(ws))",
    "            subprocess.run(['git', 'remote', 'add', 'origin', auth], cwd=str(ws))",
    "            push_res = subprocess.run(['git', 'push', '-u', 'origin', 'main'], cwd=str(ws), capture_output=True, text=True)",
    "            if push_res.returncode == 0:",
    "                db.add(EventoAuditoria(actor='GitOps', action='Workspace Sincronizado a GitHub', target=repo_name, severity='success'))",
    "            else:",
    "                db.add(EventoAuditoria(actor='GitOps', action=f'Error de Push: {push_res.stderr[:100]}', target=repo_name, severity='danger'))",
    "            await db.commit()",
    "    except Exception as e:",
    "        db.add(EventoAuditoria(actor='Sistema', action=f'Excepción Fatal GitOps: {str(e)[:100]}', target=slug, severity='danger'))",
    "        await db.commit()",
    "    return obj",
    "@router.delete('/{project_id}')",
    "async def delete_project(project_id: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    from app.routers.github import delete_repo",
    "    obj = await db.get(Proyecto, UUID(project_id))",
    "    if not obj: raise HTTPException(404)",
    "    slug = obj.nombre_slug",
    "    try:",
    "        await delete_repo(project_id, db)",
    "    except Exception as e:",
    "        db.add(EventoAuditoria(actor='Sistema', action=f'Error borrando repo Github: {str(e)[:50]}', target=slug, severity='warning'))",
    "    ws = settings.base_projects_dir / slug",
    "    if ws.exists(): shutil.rmtree(ws, ignore_errors=True)",
    "    db.add(EventoAuditoria(actor='Sistema', action='Proyecto y Workspace Destruido', target=slug, severity='danger'))",
    "    await db.delete(obj)",
    "    await db.commit()",
    "    return {'status': 'ok'}",
    "@router.get('/{project_id}/readme')",
    "async def get_readme(project_id: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    path = settings.base_projects_dir / p.nombre_slug / 'README.md'",
    "    if path.exists():",
    "        with open(path, 'r', encoding='utf-8') as f: return {'content': f.read()}",
    "    return {'content': 'Sin README.'}",
    "@router.patch('/{project_id}/readme')",
    "async def update_readme(project_id: str, payload: ReadmeUpdate, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    ws = settings.base_projects_dir / p.nombre_slug",
    "    with open(ws / 'README.md', 'w', encoding='utf-8') as f: f.write(payload.content)",
    "    return {'status': 'ok'}",
    "@router.get('/{project_id}/workspace/file')",
    "async def read_file(project_id: str, file_path: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    fp = Path(file_path)",
    "    if not fp.is_file():",
    "        fp = settings.base_projects_dir / p.nombre_slug / file_path.lstrip('./').lstrip('/')",
    "    if not fp.is_file(): return {'content': 'Archivo no existe.', 'is_image': False}",
    "    mime_type, _ = mimetypes.guess_type(str(fp))",
    "    if mime_type and mime_type.startswith('image/'):",
    "        with open(fp, 'rb') as f:",
    "            b64 = base64.b64encode(f.read()).decode('utf-8')",
    "            return {'content': f'data:{mime_type};base64,{b64}', 'is_image': True}",
    "    with open(fp, 'r', encoding='utf-8', errors='replace') as f: ",
    "        return {'content': f.read(), 'is_image': False}",
    "@router.put('/{project_id}/workspace/file')",
    "async def update_file(project_id: str, file_path: str, payload: FileUpdate, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    fp = Path(file_path)",
    "    if not fp.is_file(): fp = settings.base_projects_dir / p.nombre_slug / file_path.lstrip('./').lstrip('/')",
    "    if not fp.is_file(): raise HTTPException(404, 'Archivo no encontrado')",
    "    with open(fp, 'w', encoding='utf-8') as f: f.write(payload.content)",
    "    db.add(EventoAuditoria(actor='User', action='Archivo Editado', target=fp.name, severity='info'))",
    "    await db.commit()",
    "    return {'status': 'ok'}",
    "@router.delete('/{project_id}/workspace/file')",
    "async def delete_file(project_id: str, file_path: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    fp = Path(file_path)",
    "    if not fp.is_file(): fp = settings.base_projects_dir / p.nombre_slug / file_path.lstrip('./').lstrip('/')",
    "    if not fp.is_file(): raise HTTPException(404, 'Archivo no encontrado')",
    "    os.remove(fp)",
    "    db.add(EventoAuditoria(actor='User', action='Archivo Eliminado', target=fp.name, severity='warning'))",
    "    await db.commit()",
    "    return {'status': 'ok'}",
    "@router.get('/{project_id}/workspace/tree')",
    "async def get_tree(project_id: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    b = settings.base_projects_dir / p.nombre_slug",
    "    if not b.exists(): return []",
    "    def bt(path):",
    "        n = os.path.basename(path)",
    "        if os.path.isdir(path):",
    "            return {'id': path, 'name': n, 'type': 'folder', 'path': path, 'children': [bt(os.path.join(path, x)) for x in os.listdir(path) if not x.startswith('.git')]}",
    "        return {'id': path, 'name': n, 'type': 'file', 'path': path}",
    "    return [bt(os.path.join(b, x)) for x in os.listdir(b) if not x.startswith('.git')]",
    "@router.get('/{project_id}/messages')",
    "async def get_msgs(project_id: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models.history_models import MensajeHistorial",
    "    try:",
    "        r = await db.execute(select(MensajeHistorial).where(MensajeHistorial.proyecto_id == UUID(project_id)).order_by(MensajeHistorial.fecha_envio.asc()))",
    "        return list(r.scalars().all())",
    "    except: return []",
    "@router.get('/{project_id}', response_model=ProyectoOut)",
    "async def get_project(project_id: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    obj = await db.get(Proyecto, UUID(project_id))",
    "    if not obj: raise HTTPException(404)",
    "    return obj",
    "@router.patch('/{project_id}', response_model=ProyectoOut)",
    "async def update_project(project_id: str, payload: dict, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    obj = await db.get(Proyecto, UUID(project_id))",
    "    valid_keys = Proyecto.__table__.columns.keys()",
    "    for k, v in payload.items():",
    "        if k in valid_keys: setattr(obj, k, v)",
    "    db.add(EventoAuditoria(actor='User', action='Proyecto Actualizado', target=obj.nombre_slug, severity='info'))",
    "    await db.commit()",
    "    await db.refresh(obj)",
    "    return obj"
])

print("✅ Parche de estabilización GitOps y Auditoría aplicado.")
