import os

def w(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"✅ Reparado: {path}")

print("🚀 INICIANDO MEGA-PARCHE ENTERPRISE (SECUENCIAL)...")

# 1. MAIN.PY: Montar las tuberías que faltaban (Files y Github)
w("backend/app/main.py", [
    "from fastapi import FastAPI",
    "from fastapi.middleware.cors import CORSMiddleware",
    "from contextlib import asynccontextmanager",
    "from app.database import init_db",
    "from app.routers import projects, approvals, config, health, audit, metrics, tools, agents, websocket_chat, files, github",
    "@asynccontextmanager",
    "async def lifespan(app: FastAPI):",
    "    await init_db()",
    "    yield",
    "app = FastAPI(lifespan=lifespan)",
    "app.add_middleware(CORSMiddleware, allow_origins=['*'], allow_credentials=True, allow_methods=['*'], allow_headers=['*'])",
    "app.include_router(health.router, tags=['Health'])",
    "app.include_router(projects.router, prefix='/api/projects', tags=['Projects'])",
    "app.include_router(approvals.router, prefix='/api/approvals', tags=['Approvals'])",
    "app.include_router(config.router, prefix='/api/config', tags=['Config'])",
    "app.include_router(audit.router, prefix='/api/audit', tags=['Audit'])",
    "app.include_router(metrics.router, prefix='/api/metrics', tags=['Metrics'])",
    "app.include_router(tools.router, prefix='/api/tools', tags=['Tools'])",
    "app.include_router(agents.router, prefix='/api/agents', tags=['Agents'])",
    "app.include_router(files.router, prefix='/api/files', tags=['Files'])",
    "app.include_router(github.router, prefix='/api/github', tags=['Github'])",
    "app.include_router(websocket_chat.router, tags=['Websockets'])"
])

# 2. FILES.PY: Crear el Router de Archivos para solucionar el 404
w("backend/app/routers/files.py", [
    "import os",
    "from uuid import UUID",
    "from fastapi import APIRouter, Depends, UploadFile, File",
    "from sqlalchemy import select",
    "from app.database import get_db",
    "from app.config import get_settings",
    "from app.models import ArchivoTemporal, Proyecto",
    "router = APIRouter()",
    "settings = get_settings()",
    "@router.get('/{project_id}')",
    "async def list_files(project_id: str, db=Depends(get_db)):",
    "    res = await db.execute(select(ArchivoTemporal).where(ArchivoTemporal.proyecto_id == UUID(project_id)))",
    "    return list(res.scalars().all())",
    "@router.post('/{project_id}/upload')",
    "async def upload_file(project_id: str, file: UploadFile = File(...), db=Depends(get_db)):",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    ws = settings.base_projects_dir / p.nombre_slug / '_uploads'",
    "    ws.mkdir(parents=True, exist_ok=True)",
    "    target = ws / file.filename",
    "    content = await file.read()",
    "    with open(target, 'wb') as f: f.write(content)",
    "    obj = ArchivoTemporal(proyecto_id=UUID(project_id), nombre_archivo=file.filename, contenido_codigo='Binario', ruta_archivo=str(target), mime_type=file.content_type, size_bytes=len(content))",
    "    db.add(obj)",
    "    await db.commit()",
    "    return obj"
])

# 3. GITHUB.PY: Push Forzado a la URL directa (Fix "No origin")
w("backend/app/routers/github.py", [
    "import subprocess",
    "from uuid import UUID",
    "from fastapi import APIRouter, Depends",
    "from app.database import get_db",
    "from app.config import get_settings",
    "from app.models import Proyecto",
    "router = APIRouter()",
    "settings = get_settings()",
    "async def get_cwd(project_id, db):",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    path = settings.base_projects_dir / p.nombre_slug",
    "    path.mkdir(parents=True, exist_ok=True)",
    "    return str(path)",
    "@router.post('/{project_id}/status')",
    "async def git_status(project_id: str, db=Depends(get_db)):",
    "    cwd = await get_cwd(project_id, db)",
    "    subprocess.run(['git', 'init'], cwd=cwd)",
    "    res = subprocess.run(['git', 'status'], cwd=cwd, capture_output=True, text=True)",
    "    return {'output': res.stdout or res.stderr}",
    "@router.post('/{project_id}/add')",
    "async def git_add(project_id: str, db=Depends(get_db)):",
    "    cwd = await get_cwd(project_id, db)",
    "    res = subprocess.run(['git', 'add', '.'], cwd=cwd, capture_output=True, text=True)",
    "    return {'output': 'Archivos agregados.\\n' + (res.stdout or res.stderr)}",
    "@router.post('/{project_id}/commit')",
    "async def git_commit(project_id: str, db=Depends(get_db)):",
    "    cwd = await get_cwd(project_id, db)",
    "    subprocess.run(['git', 'config', 'user.email', 'bot@nodara.local'], cwd=cwd)",
    "    subprocess.run(['git', 'config', 'user.name', 'Nodara Bot'], cwd=cwd)",
    "    res = subprocess.run(['git', 'commit', '-m', 'Commit Nodara'], cwd=cwd, capture_output=True, text=True)",
    "    return {'output': res.stdout or res.stderr}",
    "@router.post('/{project_id}/push')",
    "async def git_push(project_id: str, db=Depends(get_db)):",
    "    cwd = await get_cwd(project_id, db)",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    if p.github_url and settings.github_personal_access_token:",
    "        tk = settings.github_personal_access_token",
    "        auth = p.github_url.replace('https://', f'https://{tk}@')",
    "        subprocess.run(['git', 'branch', '-M', 'main'], cwd=cwd)",
    "        res = subprocess.run(['git', 'push', auth, 'main'], cwd=cwd, capture_output=True, text=True)",
    "        return {'output': res.stdout or res.stderr}",
    "    return {'output': 'Error: GitOps sin configurar.'}"
])

# 4. PROJECTS.PY: Arreglando Workspace Error, Mensajes y Persistencia
w("backend/app/routers/projects.py", [
    "import os, subprocess",
    "from uuid import UUID",
    "from pathlib import Path",
    "from fastapi import APIRouter, Depends, HTTPException",
    "from sqlalchemy import select",
    "from sqlalchemy.ext.asyncio import AsyncSession",
    "from pydantic import BaseModel",
    "from app.database import get_db",
    "from app.config import get_settings",
    "from app.schemas import ProyectoCreate, ProyectoOut",
    "from app.services.slug import slugify",
    "router = APIRouter()",
    "settings = get_settings()",
    "class ReadmeUpdate(BaseModel): content: str",
    "@router.get('', response_model=list[ProyectoOut])",
    "async def list_projects(db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    res = await db.execute(select(Proyecto).order_by(Proyecto.fecha_creacion.desc()))",
    "    return list(res.scalars().all())",
    "@router.post('', response_model=ProyectoOut)",
    "async def create_project(payload: ProyectoCreate, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    slug = payload.nombre_slug or slugify(payload.titulo)",
    "    obj = Proyecto(**payload.model_dump(exclude={'nombre_slug'}), nombre_slug=slug)",
    "    db.add(obj)",
    "    await db.commit()",
    "    await db.refresh(obj)",
    "    try:",
    "        ws = settings.base_projects_dir / obj.nombre_slug",
    "        ws.mkdir(parents=True, exist_ok=True)",
    "        with open(ws / 'README.md', 'w', encoding='utf-8') as f: f.write('# ' + obj.titulo + '\\n\\n' + obj.descripcion)",
    "    except: pass",
    "    return obj",
    "@router.get('/{project_id}/readme')",
    "async def get_readme(project_id: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    path = settings.base_projects_dir / p.nombre_slug / 'README.md'",
    "    if path.exists():",
    "        with open(path, 'r', encoding='utf-8') as f: return {'content': f.read()}",
    "    return {'content': 'Sin README.'}",
    "@router.patch('/{project_id}/readme')",
    "async def update_readme(project_id: str, payload: ReadmeUpdate, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    ws = settings.base_projects_dir / p.nombre_slug",
    "    with open(ws / 'README.md', 'w', encoding='utf-8') as f: f.write(payload.content)",
    "    return {'status': 'ok'}",
    "@router.get('/{project_id}/workspace/file')",
    "async def read_file(project_id: str, file_path: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    fp = Path(file_path)",
    "    if not fp.is_file():",
    "        fp = settings.base_projects_dir / p.nombre_slug / file_path.lstrip('./').lstrip('/')",
    "    if not fp.is_file(): return {'content': 'Archivo no leible o no existe.'}",
    "    with open(fp, 'r', encoding='utf-8', errors='replace') as f: return {'content': f.read()}",
    "@router.get('/{project_id}/workspace/tree')",
    "async def get_tree(project_id: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    b = settings.base_projects_dir / p.nombre_slug",
    "    if not b.exists(): return []",
    "    def bt(path):",
    "        n = os.path.basename(path)",
    "        if os.path.isdir(path):",
    "            return {'id': path, 'name': n, 'type': 'folder', 'path': path, 'children': [bt(os.path.join(path, x)) for x in os.listdir(path) if not x.startswith('.git')]}",
    "        return {'id': path, 'name': n, 'type': 'file', 'path': path}",
    "    return [bt(os.path.join(b, x)) for x in os.listdir(b) if not x.startswith('.git')]",
    "@router.get('/{project_id}/messages')",
    "async def get_msgs(project_id: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models.history_models import MensajeHistorial",
    "    try:",
    "        r = await db.execute(select(MensajeHistorial).where(MensajeHistorial.proyecto_id == UUID(project_id)).order_by(MensajeHistorial.fecha_envio.asc()))",
    "        return list(r.scalars().all())",
    "    except: return []",
    "@router.get('/{project_id}', response_model=ProyectoOut)",
    "async def get_project(project_id: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    obj = await db.get(Proyecto, UUID(project_id))",
    "    if not obj: raise HTTPException(404)",
    "    return obj",
    "@router.patch('/{project_id}', response_model=ProyectoOut)",
    "async def update_project(project_id: str, payload: dict, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    obj = await db.get(Proyecto, UUID(project_id))",
    "    for k, v in payload.items(): setattr(obj, k, v)",
    "    await db.commit()",
    "    await db.refresh(obj)",
    "    return obj"
])

# 5. FRONTEND CONFIG: Fix 422 Undefined ID
w("frontend/features/config/ConfigView.tsx", [
    "\"use client\";",
    "import { useEffect, useState } from 'react';",
    "import { Badge } from '@/components/ui/Badge';",
    "import { Button } from '@/components/ui/Button';",
    "import { Card, CardTitle } from '@/components/ui/Card';",
    "import { SectionHeader } from '@/components/ui/SectionHeader';",
    "import { configRepository } from '@/services/repositories';",
    "export function ConfigView() {",
    "  const [config, setConfig] = useState<any>(null);",
    "  useEffect(() => { configRepository.list().then(items => setConfig(items[0] || null)); }, []);",
    "  async function toggleAutoApprove() {",
    "    const cid = config?.id ? config.id : 1;",
    "    await configRepository.patch(cid, { auto_aprobar_ejecucion: !config?.auto_aprobar_ejecucion });",
    "    setConfig({...config, auto_aprobar_ejecucion: !config?.auto_aprobar_ejecucion});",
    "  }",
    "  return (",
    "    <div>",
    "      <SectionHeader title='Configuración operacional' description='Control BYOK.' />",
    "      <div className='grid gap-6 xl:grid-cols-[.8fr_1.2fr]'>",
    "        <Card>",
    "          <CardTitle eyebrow='Usuario' title={`ID ${config?.id ?? '1'}`} />",
    "          <div className='space-y-4'>",
    "            <div className='flex justify-between p-4 bg-brand-soft rounded-2xl'>",
    "              <span className='font-bold'>Auto aprobar ejecución</span>",
    "              <Badge tone={config?.auto_aprobar_ejecucion ? 'success' : 'warning'}>{config?.auto_aprobar_ejecucion ? 'ON' : 'OFF'}</Badge>",
    "            </div>",
    "            <Button onClick={toggleAutoApprove} className='w-full'>Alternar Auto Aprobación</Button>",
    "          </div>",
    "        </Card>",
    "        <Card>",
    "          <CardTitle eyebrow='BYOK' title='Estado de API Keys y saldos' />",
    "          <div className='grid gap-4 md:grid-cols-3'>",
    "            {[['OpenAI', config?.has_api_key_openai, config?.saldo_virtual_openai],",
    "              ['Anthropic', config?.has_api_key_anthropic, config?.saldo_virtual_anthropic],",
    "              ['Gemini', config?.has_api_key_gemini, config?.saldo_virtual_gemini]].map(([name, has, s]) => (",
    "              <div key={String(name)} className='rounded-3xl border bg-white p-5'>",
    "                <div className='text-lg font-black'>{String(name)}</div>",
    "                <Badge tone={has ? 'success' : 'danger'} className='mt-3'>{has ? 'Cargada' : 'Falta Key'}</Badge>",
    "              </div>",
    "            ))}",
    "            <div className='rounded-3xl border bg-white p-5 col-span-3'>",
    "              <div className='text-lg font-black'>GitHub GitOps</div>",
    "              <Badge tone={config?.has_api_key_github ? 'success' : 'danger'} className='mt-3'>",
    "                {config?.has_api_key_github ? 'Token Cargado en .env' : 'Falta GITHUB_PERSONAL_ACCESS_TOKEN'}",
    "              </Badge>",
    "            </div>",
    "          </div>",
    "        </Card>",
    "      </div>",
    "    </div>",
    "  );",
    "}"
])

# 6. FRONTEND PROJECT DETAIL: Persistencia de Roles Aislada
w("frontend/features/projects/ProjectDetailView.tsx", [
    "\"use client\";",
    "import Link from 'next/link';",
    "import { useEffect, useState } from 'react';",
    "import { Badge } from '@/components/ui/Badge';",
    "import { Button } from '@/components/ui/Button';",
    "import { Card, CardTitle } from '@/components/ui/Card';",
    "import { SectionHeader } from '@/components/ui/SectionHeader';",
    "import { projectsRepository, futureRepository } from '@/services/repositories';",
    "export function ProjectDetailView({ projectId }: { projectId: string }) {",
    "  const [project, setProject] = useState<any>(null);",
    "  const [readme, setReadme] = useState('');",
    "  const [editReadme, setEditReadme] = useState(false);",
    "  const [tempReadme, setTempReadme] = useState('');",
    "  const [editRole, setEditRole] = useState<string | null>(null);",
    "  const [tempRole, setTempRole] = useState('');",
    "  const loadData = async () => {",
    "      const p = await projectsRepository.get(projectId);",
    "      setProject(p);",
    "      const r = await futureRepository.readme(projectId);",
    "      setReadme(r?.content || 'No hay README');",
    "  };",
    "  useEffect(() => { loadData(); }, [projectId]);",
    "  const saveRole = async (key: string) => {",
    "    await projectsRepository.patch(projectId, { [key]: tempRole });",
    "    setProject({...project, [key]: tempRole});",
    "    setEditRole(null);",
    "  };",
    "  const saveReadme = async () => {",
    "    await futureRepository.updateReadme(projectId, tempReadme);",
    "    setReadme(tempReadme);",
    "    setEditReadme(false);",
    "  };",
    "  if (!project) return <p>Cargando...</p>;",
    "  return (",
    "    <div>",
    "      <SectionHeader title={project.titulo} description={project.descripcion} action={<Link href={`/chat/${project.id}`}><Button>Abrir Chat</Button></Link>} />",
    "      <div className='grid gap-6 xl:grid-cols-[1.1fr_.9fr]'>",
    "        <div className='space-y-6'>",
    "          <Card>",
    "            <div className='flex justify-between items-center mb-4'>",
    "              <CardTitle eyebrow={project.nombre_slug} title='README.md' />",
    "              <Button variant='secondary' onClick={() => { setTempReadme(readme); setEditReadme(!editReadme); }}>{editReadme ? 'Cancelar' : 'Editar'}</Button>",
    "            </div>",
    "            {editReadme ? (",
    "              <div className='space-y-3'>",
    "                <textarea className='w-full min-h-[300px] p-4 bg-brand-deep text-brand-bright font-mono text-xs rounded-xl' value={tempReadme} onChange={e => setTempReadme(e.target.value)} />",
    "                <Button onClick={saveReadme}>Guardar</Button>",
    "              </div>",
    "            ) : (",
    "              <pre className='p-4 bg-brand-soft rounded-xl text-sm whitespace-pre-wrap'>{readme}</pre>",
    "            )}",
    "          </Card>",
    "          <Card>",
    "             <CardTitle eyebrow='Metadata' title='Detalles' />",
    "             <pre className='mt-5 overflow-auto rounded-3xl bg-brand-deep p-5 text-xs leading-6 text-brand-bright'>{JSON.stringify({ tecnologias: project.tecnologias, microservicios: project.microservicios }, null, 2)}</pre>",
    "          </Card>",
    "        </div>",
    "        <Card>",
    "          <CardTitle eyebrow='Roles' title='Sala multi-agente' />",
    "          <div className='space-y-4 mt-4'>",
    "            {[['rol_gemini', 'Gemini · Infra'], ['rol_chatgpt', 'ChatGPT · Backend'], ['rol_claude', 'Claude · Frontend']].map(([key, label]) => (",
    "              <div key={key} className='p-3 border border-brand-border rounded-xl bg-brand-soft'>",
    "                <div className='flex justify-between items-center'>",
    "                  <span className='font-bold text-sm text-brand-navy'>{label}</span>",
    "                  <button className='text-brand-cyan text-xs font-black uppercase' onClick={() => { setEditRole(key); setTempRole(project[key]); }}>Editar</button>",
    "                </div>",
    "                {editRole === key ? (",
    "                  <div className='mt-3 flex flex-col gap-2'>",
    "                    <textarea className='w-full text-xs p-2 border rounded-xl h-20' value={tempRole} onChange={e => setTempRole(e.target.value)} />",
    "                    <Button onClick={() => saveRole(key)}>Guardar Rol</Button>",
    "                  </div>",
    "                ) : (",
    "                  <p className='text-xs text-brand-muted mt-2'>{project[key]}</p>",
    "                )}",
    "              </div>",
    "            ))}",
    "          </div>",
    "        </Card>",
    "      </div>",
    "    </div>",
    "  );",
    "}"
])

# 7. FRONTEND CHAT: Permitir pegar imágenes OnPaste y subir archivos
w("frontend/features/chat/MultiAgentChat.tsx", [
    "\"use client\";",
    "import { useEffect, useRef, useState } from 'react';",
    "import { Badge } from '@/components/ui/Badge';",
    "import { Button } from '@/components/ui/Button';",
    "import { Card, CardTitle } from '@/components/ui/Card';",
    "import { WS_BASE_URL } from '@/lib/env';",
    "import { filesRepository } from '@/services/repositories';",
    "export function MultiAgentChat({ projectId }: { projectId: string }) {",
    "  const [input, setInput] = useState('');",
    "  const [events, setEvents] = useState<any[]>([]);",
    "  const [status, setStatus] = useState('closed');",
    "  const wsRef = useRef<WebSocket | null>(null);",
    "  useEffect(() => {",
    "    const wsUrl = `${WS_BASE_URL}/ws/chat/${projectId}?usuario_config_id=1`;",
    "    const socket = new WebSocket(wsUrl);",
    "    wsRef.current = socket;",
    "    socket.onopen = () => setStatus('open');",
    "    socket.onclose = () => setStatus('closed');",
    "    socket.onmessage = (event) => {",
    "      try {",
    "        const raw = JSON.parse(event.data);",
    "        setEvents(prev => [...prev, { type: raw.event, agent: raw.data?.agent, message: raw.data?.message }]);",
    "      } catch {}",
    "    };",
    "    return () => socket.close();",
    "  }, [projectId]);",
    "  function send() {",
    "    if (!input.trim() || !wsRef.current) return;",
    "    wsRef.current.send(JSON.stringify({ message: input, correlation_id: crypto.randomUUID() }));",
    "    setInput('');",
    "  }",
    "  const uploadFile = async (file: File) => {",
    "    try {",
    "      await filesRepository.upload(projectId, file);",
    "      setInput(`[Archivo Subido: ${file.name}] Por favor analízalo.`);",
    "    } catch(err) { console.error('Upload Error', err); }",
    "  };",
    "  const handlePaste = (e: React.ClipboardEvent) => {",
    "    const items = e.clipboardData.items;",
    "    for (let i = 0; i < items.length; i++) {",
    "      if (items[i].type.indexOf('image') !== -1) {",
    "        const file = items[i].getAsFile();",
    "        if (file) uploadFile(file);",
    "      }",
    "    }",
    "  };",
    "  return (",
    "    <div className='grid gap-6 xl:grid-cols-[1fr_300px]'>",
    "      <Card className='min-h-[600px] flex flex-col'>",
    "        <CardTitle eyebrow='Conversación' title='Sala de orquestación' action={<Badge>{status}</Badge>} />",
    "        <div className='flex-1 overflow-y-auto bg-brand-soft rounded-2xl p-4 mt-4 space-y-4'>",
    "          {events.map((e, i) => (",
    "            <div key={i} className='bg-white p-3 rounded-xl shadow-sm'>",
    "              <span className='font-bold text-xs text-brand-cyan uppercase'>{e.type}</span>",
    "              {e.agent && <span className='ml-2 text-xs font-bold text-brand-navy'>[{e.agent}]</span>}",
    "              <p className='mt-2 text-sm whitespace-pre-wrap'>{e.message}</p>",
    "            </div>",
    "          ))}",
    "        </div>",
    "        <div className='mt-4 flex gap-2 items-center'>",
    "          <label className='cursor-pointer bg-brand-soft px-4 py-3 rounded-2xl border text-sm font-bold hover:bg-brand-border transition'>",
    "            📎 Subir",
    "            <input type='file' className='hidden' onChange={e => e.target.files?.[0] && uploadFile(e.target.files[0])} />",
    "          </label>",
    "          <input className='flex-1 rounded-2xl border px-4 py-3' placeholder='Pega (Ctrl+V) una imagen o texto...' value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && send()} onPaste={handlePaste} />",
    "          <Button onClick={send}>Enviar</Button>",
    "        </div>",
    "      </Card>",
    "    </div>",
    "  );",
    "}"
])

print("✅ Todos los archivos fueron reconstruidos.")
