import os

def w(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"✅ Reconstruido: {path}")

print("🚀 INICIANDO MEGA-PARCHE ENTERPRISE DEFINITIVO...")

# 1. FIX GITHUB ROUTER: Auto-creación, Push y Eliminación de Repo
w("backend/app/routers/github.py", [
    "import subprocess, httpx, shutil",
    "from uuid import UUID",
    "from fastapi import APIRouter, Depends",
    "from app.database import get_db",
    "from app.config import get_settings",
    "from app.models import Proyecto",
    "router = APIRouter()",
    "settings = get_settings()",
    "async def get_cwd(project_id, db):",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    path = settings.base_projects_dir / p.nombre_slug",
    "    path.mkdir(parents=True, exist_ok=True)",
    "    return str(path)",
    "@router.post('/{project_id}/status')",
    "async def git_status(project_id: str, db=Depends(get_db)):",
    "    cwd = await get_cwd(project_id, db)",
    "    subprocess.run(['git', 'init'], cwd=cwd)",
    "    res = subprocess.run(['git', 'status'], cwd=cwd, capture_output=True, text=True)",
    "    return {'output': res.stdout or res.stderr}",
    "@router.post('/{project_id}/add')",
    "async def git_add(project_id: str, db=Depends(get_db)):",
    "    cwd = await get_cwd(project_id, db)",
    "    res = subprocess.run(['git', 'add', '.'], cwd=cwd, capture_output=True, text=True)",
    "    return {'output': 'Archivos agregados.\\n' + (res.stdout or res.stderr)}",
    "@router.post('/{project_id}/commit')",
    "async def git_commit(project_id: str, db=Depends(get_db)):",
    "    cwd = await get_cwd(project_id, db)",
    "    subprocess.run(['git', 'config', 'user.email', 'bot@nodara.local'], cwd=cwd)",
    "    subprocess.run(['git', 'config', 'user.name', 'Nodara Bot'], cwd=cwd)",
    "    res = subprocess.run(['git', 'commit', '-m', 'Commit Automático Nodara'], cwd=cwd, capture_output=True, text=True)",
    "    return {'output': res.stdout or res.stderr}",
    "@router.post('/{project_id}/push')",
    "async def git_push(project_id: str, db=Depends(get_db)):",
    "    from app.models.governance import EventoAuditoria",
    "    cwd = await get_cwd(project_id, db)",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    tk = settings.github_personal_access_token",
    "    if not tk or not p.github_url: return {'output': 'Error: GitOps sin configurar.'}",
    "    slug = p.nombre_slug",
    "    is_private = p.estado != 'publico'  # Asumimos privado por defecto a menos que el estado sea 'publico'",
    "    async with httpx.AsyncClient() as client:",
    "        headers = {'Authorization': f'token {tk}', 'Accept': 'application/vnd.github.v3+json'}",
    "        r = await client.post('https://api.github.com/user/repos', headers=headers, json={'name': slug, 'private': is_private, 'description': p.descripcion})",
    "    auth = p.github_url.replace('https://', f'https://{tk}@')",
    "    subprocess.run(['git', 'branch', '-M', 'main'], cwd=cwd)",
    "    res = subprocess.run(['git', 'push', auth, 'main'], cwd=cwd, capture_output=True, text=True)",
    "    if res.returncode == 0:",
    "        audit = EventoAuditoria(actor='Sistema', action='Git Push', target=slug, severity='success')",
    "        db.add(audit)",
    "        await db.commit()",
    "    return {'output': f'Repo creado/verificado. Push:\\n{res.stdout or res.stderr}'}",
    "@router.delete('/{project_id}/repo')",
    "async def delete_repo(project_id: str, db=Depends(get_db)):",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    tk = settings.github_personal_access_token",
    "    if tk and p.github_url:",
    "        slug = p.nombre_slug",
    "        # Asumimos que la URL es tipo https://github.com/Usuario/Repo.git",
    "        # Extraemos el propietario del repo",
    "        parts = p.github_url.split('/')",
    "        if len(parts) >= 4:",
    "            owner = parts[3]",
    "            async with httpx.AsyncClient() as client:",
    "                headers = {'Authorization': f'token {tk}', 'Accept': 'application/vnd.github.v3+json'}",
    "                await client.delete(f'https://api.github.com/repos/{owner}/{slug}', headers=headers)",
    "    return {'status': 'ok'}"
])

# 2. FIX PROJECTS ROUTER: Delete completo (Workspace + Repo) y File Edit/Delete
w("backend/app/routers/projects.py", [
    "import os, subprocess, base64, mimetypes, shutil",
    "from uuid import UUID",
    "from pathlib import Path",
    "from fastapi import APIRouter, Depends, HTTPException",
    "from sqlalchemy import select",
    "from sqlalchemy.ext.asyncio import AsyncSession",
    "from pydantic import BaseModel",
    "from app.database import get_db",
    "from app.config import get_settings",
    "from app.schemas import ProyectoCreate, ProyectoOut",
    "from app.services.slug import slugify",
    "from app.routers.github import delete_repo",
    "router = APIRouter()",
    "settings = get_settings()",
    "class ReadmeUpdate(BaseModel): content: str",
    "class FileUpdate(BaseModel): content: str",
    "@router.get('', response_model=list[ProyectoOut])",
    "async def list_projects(db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    res = await db.execute(select(Proyecto).order_by(Proyecto.fecha_creacion.desc()))",
    "    return list(res.scalars().all())",
    "@router.post('', response_model=ProyectoOut)",
    "async def create_project(payload: ProyectoCreate, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    slug = payload.nombre_slug or slugify(payload.titulo)",
    "    data = payload.model_dump()",
    "    valid_keys = Proyecto.__table__.columns.keys()",
    "    filtered_data = {k: v for k, v in data.items() if k in valid_keys and k != 'nombre_slug'}",
    "    obj = Proyecto(**filtered_data, nombre_slug=slug)",
    "    db.add(obj)",
    "    await db.commit()",
    "    await db.refresh(obj)",
    "    try:",
    "        ws = settings.base_projects_dir / obj.nombre_slug",
    "        ws.mkdir(parents=True, exist_ok=True)",
    "        with open(ws / 'README.md', 'w', encoding='utf-8') as f: ",
    "            f.write('# ' + obj.titulo + '\\n\\n' + obj.descripcion)",
    "    except: pass",
    "    return obj",
    "@router.delete('/{project_id}')",
    "async def delete_project(project_id: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    obj = await db.get(Proyecto, UUID(project_id))",
    "    if not obj: raise HTTPException(404)",
    "    # 1. Borrar Repo en GitHub",
    "    await delete_repo(project_id, db)",
    "    # 2. Borrar Workspace físico",
    "    ws = settings.base_projects_dir / obj.nombre_slug",
    "    if ws.exists(): shutil.rmtree(ws)",
    "    # 3. Borrar de DB (Cascada asume borrar Mensajes y Archivos)",
    "    await db.delete(obj)",
    "    await db.commit()",
    "    return {'status': 'ok'}",
    "@router.get('/{project_id}/readme')",
    "async def get_readme(project_id: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    path = settings.base_projects_dir / p.nombre_slug / 'README.md'",
    "    if path.exists():",
    "        with open(path, 'r', encoding='utf-8') as f: return {'content': f.read()}",
    "    return {'content': 'Sin README.'}",
    "@router.patch('/{project_id}/readme')",
    "async def update_readme(project_id: str, payload: ReadmeUpdate, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    ws = settings.base_projects_dir / p.nombre_slug",
    "    with open(ws / 'README.md', 'w', encoding='utf-8') as f: f.write(payload.content)",
    "    return {'status': 'ok'}",
    "@router.get('/{project_id}/workspace/file')",
    "async def read_file(project_id: str, file_path: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    fp = Path(file_path)",
    "    if not fp.is_file():",
    "        fp = settings.base_projects_dir / p.nombre_slug / file_path.lstrip('./').lstrip('/')",
    "    if not fp.is_file(): return {'content': 'Archivo no leible o no existe.', 'is_image': False}",
    "    mime_type, _ = mimetypes.guess_type(str(fp))",
    "    if mime_type and mime_type.startswith('image/'):",
    "        with open(fp, 'rb') as f:",
    "            b64 = base64.b64encode(f.read()).decode('utf-8')",
    "            return {'content': f'data:{mime_type};base64,{b64}', 'is_image': True}",
    "    with open(fp, 'r', encoding='utf-8', errors='replace') as f: ",
    "        return {'content': f.read(), 'is_image': False}",
    "@router.put('/{project_id}/workspace/file')",
    "async def update_file(project_id: str, file_path: str, payload: FileUpdate, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    fp = Path(file_path)",
    "    if not fp.is_file():",
    "        fp = settings.base_projects_dir / p.nombre_slug / file_path.lstrip('./').lstrip('/')",
    "    if not fp.is_file(): raise HTTPException(404, 'Archivo no encontrado')",
    "    with open(fp, 'w', encoding='utf-8') as f: f.write(payload.content)",
    "    return {'status': 'ok'}",
    "@router.delete('/{project_id}/workspace/file')",
    "async def delete_file(project_id: str, file_path: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    fp = Path(file_path)",
    "    if not fp.is_file():",
    "        fp = settings.base_projects_dir / p.nombre_slug / file_path.lstrip('./').lstrip('/')",
    "    if not fp.is_file(): raise HTTPException(404, 'Archivo no encontrado')",
    "    os.remove(fp)",
    "    return {'status': 'ok'}",
    "@router.get('/{project_id}/workspace/tree')",
    "async def get_tree(project_id: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    p = await db.get(Proyecto, UUID(project_id))",
    "    b = settings.base_projects_dir / p.nombre_slug",
    "    if not b.exists(): return []",
    "    def bt(path):",
    "        n = os.path.basename(path)",
    "        if os.path.isdir(path):",
    "            return {'id': path, 'name': n, 'type': 'folder', 'path': path, 'children': [bt(os.path.join(path, x)) for x in os.listdir(path) if not x.startswith('.git')]}",
    "        return {'id': path, 'name': n, 'type': 'file', 'path': path}",
    "    return [bt(os.path.join(b, x)) for x in os.listdir(b) if not x.startswith('.git')]",
    "@router.get('/{project_id}/messages')",
    "async def get_msgs(project_id: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models.history_models import MensajeHistorial",
    "    try:",
    "        r = await db.execute(select(MensajeHistorial).where(MensajeHistorial.proyecto_id == UUID(project_id)).order_by(MensajeHistorial.fecha_envio.asc()))",
    "        return list(r.scalars().all())",
    "    except: return []",
    "@router.get('/{project_id}', response_model=ProyectoOut)",
    "async def get_project(project_id: str, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    obj = await db.get(Proyecto, UUID(project_id))",
    "    if not obj: raise HTTPException(404)",
    "    return obj",
    "@router.patch('/{project_id}', response_model=ProyectoOut)",
    "async def update_project(project_id: str, payload: dict, db: AsyncSession = Depends(get_db)):",
    "    from app.models import Proyecto",
    "    obj = await db.get(Proyecto, UUID(project_id))",
    "    valid_keys = Proyecto.__table__.columns.keys()",
    "    for k, v in payload.items():",
    "        if k in valid_keys: setattr(obj, k, v)",
    "    await db.commit()",
    "    await db.refresh(obj)",
    "    return obj"
])

# 3. FIX AUDIT ROUTER: Para que no devuelva mocks y lea de DB
w("backend/app/routers/audit.py", [
    "from fastapi import APIRouter, Depends",
    "from sqlalchemy import select",
    "from sqlalchemy.ext.asyncio import AsyncSession",
    "from app.database import get_db",
    "from app.models.governance import EventoAuditoria",
    "router = APIRouter()",
    "@router.get('/events')",
    "async def get_audit(db: AsyncSession = Depends(get_db)):",
    "    try:",
    "        res = await db.execute(select(EventoAuditoria).order_by(EventoAuditoria.fecha_evento.desc()))",
    "        return list(res.scalars().all())",
    "    except:",
    "        return []"
])

# 4. FIX FRONTEND REPOSITORIES: Agregando métodos DELETE y PUT faltantes
w("frontend/services/repositories.ts", [
    "const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';",
    "async function fetchAPI(end: string, opts?: RequestInit) {",
    "  const res = await fetch(`${API}${end}`, {",
    "    ...opts, headers: { 'Content-Type': 'application/json', ...opts?.headers }",
    "  });",
    "  if(!res.ok) throw new Error(`HTTP ${res.status}`);",
    "  return await res.json();",
    "}",
    "function norm(d: any) { return Array.isArray(d) ? d : (d?.data || d?.items || []); }",
    "export const projectsRepository = {",
    "  list: async () => norm(await fetchAPI('/api/projects')),",
    "  get: async (id: string) => await fetchAPI(`/api/projects/${id}`),",
    "  create: async (p: any) => await fetchAPI('/api/projects', { method: 'POST', body: JSON.stringify(p) }),",
    "  patch: async (id: string, p: any) => await fetchAPI(`/api/projects/${id}`, { method: 'PATCH', body: JSON.stringify(p) }),",
    "  delete: async (id: string) => await fetchAPI(`/api/projects/${id}`, { method: 'DELETE' })",
    "};",
    "export const futureRepository = {",
    "  messages: async (id: string) => norm(await fetchAPI(`/api/projects/${id}/messages`)),",
    "  workspace: async (id: string) => norm(await fetchAPI(`/api/projects/${id}/workspace/tree`)),",
    "  workspaceFile: async (id: string, path: string) => await fetchAPI(`/api/projects/${id}/workspace/file?file_path=${encodeURIComponent(path)}`),",
    "  updateWorkspaceFile: async (id: string, path: string, content: string) => await fetchAPI(`/api/projects/${id}/workspace/file?file_path=${encodeURIComponent(path)}`, { method: 'PUT', body: JSON.stringify({ content }) }),",
    "  deleteWorkspaceFile: async (id: string, path: string) => await fetchAPI(`/api/projects/${id}/workspace/file?file_path=${encodeURIComponent(path)}`, { method: 'DELETE' }),",
    "  readme: async (id: string) => await fetchAPI(`/api/projects/${id}/readme`),",
    "  updateReadme: async (id: string, c: string) => await fetchAPI(`/api/projects/${id}/readme`, { method: 'PATCH', body: JSON.stringify({ content: c }) }),",
    "  metrics: async () => norm(await fetchAPI('/api/metrics')),",
    "  agents: async () => norm(await fetchAPI('/api/agents')),",
    "  tools: async () => norm(await fetchAPI('/api/tools')),",
    "  audit: async () => norm(await fetchAPI('/api/audit/events'))",
    "};",
    "export const githubRepository = {",
    "  status: async (id: string) => await fetchAPI(`/api/github/${id}/status`, { method: 'POST' }),",
    "  add: async (id: string) => await fetchAPI(`/api/github/${id}/add`, { method: 'POST' }),",
    "  commit: async (id: string) => await fetchAPI(`/api/github/${id}/commit`, { method: 'POST' }),",
    "  push: async (id: string) => await fetchAPI(`/api/github/${id}/push`, { method: 'POST' })",
    "};",
    "export const filesRepository = {",
    "  list: async (id: string) => norm(await fetchAPI(`/api/files/${id}`)),",
    "  upload: async (id: string, file: File) => {",
    "    const data = new FormData();",
    "    data.append('file', file);",
    "    const res = await fetch(`${API}/api/files/${id}/upload`, { method: 'POST', body: data });",
    "    return await res.json();",
    "  }",
    "};",
    "export const configRepository = {",
    "  list: async () => norm(await fetchAPI('/api/config')),",
    "  patch: async (id: number, p: any) => await fetchAPI(`/api/config/${id}`, { method: 'PATCH', body: JSON.stringify(p) })",
    "};",
    "export const approvalsRepository = {",
    "  listAll: async () => norm(await fetchAPI('/api/approvals')),",
    "  approve: async (id: number) => await fetchAPI(`/api/approvals/${id}/approve`, { method: 'POST' }),",
    "  reject: async (id: number) => await fetchAPI(`/api/approvals/${id}/reject`, { method: 'POST' })",
    "};"
])

# 5. FIX FRONTEND FUTURE TABLES: Edición/Eliminación Workspace y Visibilidad Git
w("frontend/features/future/FutureTables.tsx", [
    "\"use client\";",
    "import { useEffect, useState } from 'react';",
    "import { Badge } from '@/components/ui/Badge';",
    "import { Button } from '@/components/ui/Button';",
    "import { Card, CardTitle } from '@/components/ui/Card';",
    "import { SectionHeader } from '@/components/ui/SectionHeader';",
    "import { futureRepository, projectsRepository, githubRepository } from '@/services/repositories';",
    "import { formatDate } from '@/lib/format';",
    "function ProjectSelector({ projects, projectId, setProjectId }: any) {",
    "    if (projects.length === 0) return null;",
    "    return (",
    "        <div className='mb-6'>",
    "            <label className='mr-4 font-bold text-sm'>Seleccionar Proyecto:</label>",
    "            <select className='border border-brand-border bg-white p-2 rounded-xl text-sm' value={projectId} onChange={(e) => setProjectId(e.target.value)}>",
    "                {projects.map((p:any) => <option key={p.id} value={p.id}>{p.titulo}</option>)}",
    "            </select>",
    "        </div>",
    "    );",
    "}",
    "export function AgentsView() {",
    "  const [projects, setProjects] = useState<any[]>([]);",
    "  const [projectId, setProjectId] = useState<string>('');",
    "  const [project, setProject] = useState<any>(null);",
    "  const [edit, setEdit] = useState<string | null>(null);",
    "  const [temp, setTemp] = useState('');",
    "  useEffect(() => { projectsRepository.list().then(p => { setProjects(p); if(p.length > 0) setProjectId(p[0].id); }); }, []);",
    "  useEffect(() => { if(projectId) projectsRepository.get(projectId).then(setProject); }, [projectId]);",
    "  const save = async (key: string) => {",
    "    await projectsRepository.patch(projectId, { [key]: temp });",
    "    setProject({...project, [key]: temp}); setEdit(null);",
    "  };",
    "  return (",
    "    <div>",
    "      <SectionHeader title='Gestión de agentes' description='Roles por proyecto.' />",
    "      <ProjectSelector projects={projects} projectId={projectId} setProjectId={setProjectId} />",
    "      {project && (",
    "        <div className='grid gap-5 xl:grid-cols-3'>",
    "          {[['rol_gemini','Gemini'],['rol_chatgpt','ChatGPT'],['rol_claude','Claude']].map(([k, n]) => (",
    "            <Card key={k}><Badge tone='success'>{n}</Badge>",
    "            <div className='flex justify-between mt-3'><h3 className='font-black text-xl'>Rol</h3><button className='text-brand-cyan text-xs font-black uppercase' onClick={() => {setEdit(k); setTemp(project[k]);}}>Editar</button></div>",
    "            {edit === k ? <div className='mt-2'><textarea className='w-full text-xs p-2 border rounded' value={temp} onChange={e => setTemp(e.target.value)} /><Button onClick={() => save(k)}>Guardar</Button></div> : <p className='mt-2 text-sm text-brand-muted'>{project[k]}</p>}",
    "            </Card>",
    "          ))}",
    "        </div>",
    "      )}",
    "    </div>",
    "  );",
    "}",
    "function Tree({ nodes, depth = 0, onFileClick, onDeleteClick }: any) {",
    "  return (",
    "    <div className='space-y-1 mt-2'>",
    "      {nodes.map((node: any) => (",
    "        <div key={node.id} style={{ marginLeft: depth * 20 }} className='group'>",
    "          <div className={`px-2 py-1 text-sm rounded flex justify-between items-center ${node.type === 'file' ? 'hover:bg-brand-soft text-brand-cyan' : 'font-bold text-brand-navy'}`}>",
    "            <span className='cursor-pointer flex-1' onClick={() => node.type === 'file' && onFileClick(node.path)}> {node.type === 'folder' ? '📁' : '📄'} {node.name} </span>",
    "            {node.type === 'file' && <button onClick={() => onDeleteClick(node.path)} className='hidden group-hover:block text-red-500 text-xs font-bold'>X</button>}",
    "          </div>",
    "          {node.children && <Tree nodes={node.children} depth={depth + 1} onFileClick={onFileClick} onDeleteClick={onDeleteClick} />}",
    "        </div>",
    "      ))}",
    "    </div>",
    "  );",
    "}",
    "export function WorkspaceView() {",
    "  const [items, setItems] = useState<any[]>([]);",
    "  const [projects, setProjects] = useState<any[]>([]);",
    "  const [projectId, setProjectId] = useState<string>('');",
    "  const [fileData, setFileData] = useState<any>({content: '', is_image: false, path: ''});",
    "  const [tempContent, setTempContent] = useState('');",
    "  useEffect(() => { projectsRepository.list().then(p => { setProjects(p); if(p.length > 0) setProjectId(p[0].id); }); }, []);",
    "  const loadTree = () => { if (projectId) { futureRepository.workspace(projectId).then(setItems); setFileData({content: '', is_image: false, path: ''}); } };",
    "  useEffect(() => { loadTree(); }, [projectId]);",
    "  const handleFileClick = async (path: string) => {",
    "      const res = await futureRepository.workspaceFile(projectId, path);",
    "      setFileData({ content: res?.content || '', is_image: res?.is_image, path });",
    "      setTempContent(res?.content || '');",
    "  };",
    "  const handleSave = async () => {",
    "      if(fileData.path) { await futureRepository.updateWorkspaceFile(projectId, fileData.path, tempContent); alert('Guardado'); }",
    "  };",
    "  const handleDelete = async (path: string) => {",
    "      if(confirm('¿Eliminar archivo?')) { await futureRepository.deleteWorkspaceFile(projectId, path); loadTree(); }",
    "  };",
    "  return (",
    "    <div>",
    "      <SectionHeader title='Workspace' description='Edita o elimina archivos físicamente.' />",
    "      <ProjectSelector projects={projects} projectId={projectId} setProjectId={setProjectId} />",
    "      <div className='grid xl:grid-cols-[300px_1fr] gap-6'>",
    "        <Card>",
    "          <CardTitle title='Explorador' />",
    "          <Tree nodes={items} onFileClick={handleFileClick} onDeleteClick={handleDelete} />",
    "        </Card>",
    "        <Card>",
    "           <div className='flex justify-between items-center mb-4'>",
    "             <CardTitle title='Visualizador / Editor' />",
    "             {!fileData.is_image && fileData.path && <Button onClick={handleSave}>Guardar Fichero</Button>}",
    "           </div>",
    "           <div className='mt-4 p-4 bg-brand-deep text-brand-bright rounded-xl overflow-auto max-h-[600px] flex items-center justify-center min-h-[100px]'>",
    "              {fileData.is_image ? <img src={fileData.content} className='max-w-full rounded shadow-xl' alt='Preview' /> : <textarea className='w-full min-h-[300px] bg-transparent outline-none text-xs font-mono' value={tempContent} onChange={e => setTempContent(e.target.value)} placeholder='Selecciona archivo...' />}",
    "           </div>",
    "        </Card>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "export function GithubView() {",
    "  const [projects, setProjects] = useState<any[]>([]);",
    "  const [projectId, setProjectId] = useState<string>('');",
    "  const [output, setOutput] = useState<string>('');",
    "  useEffect(() => { projectsRepository.list().then(p => { setProjects(p); if(p.length > 0) setProjectId(p[0].id); }); }, []);",
    "  const runCmd = async (action: 'status' | 'add' | 'commit' | 'push') => {",
    "      setOutput('Ejecutando...');",
    "      try {",
    "          const res = await githubRepository[action](projectId);",
    "          setOutput(res?.output || 'Ejecutado con éxito.');",
    "      } catch (e) { setOutput('Error.'); }",
    "  };",
    "  return (",
    "    <div>",
    "      <SectionHeader title='GitOps' description='Control de versiones con Push Automático.' />",
    "      <ProjectSelector projects={projects} projectId={projectId} setProjectId={setProjectId} />",
    "      <Card>",
    "        <div className='flex gap-2 mb-4'>",
    "            <Button variant='secondary' onClick={() => runCmd('status')}>Git Status</Button>",
    "            <Button variant='secondary' onClick={() => runCmd('add')}>Git Add .</Button>",
    "            <Button variant='secondary' onClick={() => runCmd('commit')}>Git Commit</Button>",
    "            <Button onClick={() => runCmd('push')}>Git Push (API)</Button>",
    "        </div>",
    "        <pre className='bg-brand-deep text-brand-bright p-4 rounded-xl text-sm whitespace-pre-wrap'>{output}</pre>",
    "      </Card>",
    "    </div>",
    "  );",
    "}",
    "export function MetricsView() {",
    "  const [items, setItems] = useState<any[]>([]);",
    "  useEffect(() => { futureRepository.metrics().then(setItems); }, []);",
    "  return (",
    "    <div>",
    "      <SectionHeader title='Métricas' description='Dashboard.' />",
    "      <div className='grid gap-5 md:grid-cols-3'>",
    "        {items.map((m, i) => (",
    "        <Card key={i}>",
    "            <p className='text-sm font-bold text-brand-muted'>{m.label}</p>",
    "            <p className='mt-3 text-3xl font-black'>{m.value}</p>",
    "            <Badge tone={m.tone} className='mt-4'>{m.trend}</Badge>",
    "        </Card>",
    "        ))}",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "export function AuditView() {",
    "  const [items, setItems] = useState<any[]>([]);",
    "  useEffect(() => { futureRepository.audit().then(setItems); }, []);",
    "  return (",
    "    <div><SectionHeader title='Auditoría' description='Logs reales de la BD' />",
    "      <div className='space-y-4'>",
    "        {items.length === 0 ? <p>No hay eventos de auditoría registrados.</p> : items.map((a:any) => (",
    "        <Card key={a.id}><Badge tone={a.severity}>{a.severity}</Badge>",
    "            <h3 className='mt-3 font-black'>{a.action}</h3>",
    "            <p className='mt-1 text-sm text-brand-muted'>{a.actor} · {a.target}</p>",
    "            <p className='mt-1 text-xs text-brand-muted'>{formatDate(a.fecha_evento)}</p>",
    "        </Card>",
    "        ))}",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "export function ToolsView() {",
    "  const [items, setItems] = useState<any[]>([]);",
    "  useEffect(() => { futureRepository.tools().then(setItems); }, []);",
    "  return (",
    "    <div><SectionHeader title='Catálogo Tools' description='Lectura libre vs escritura con HIL.' />",
    "      <div className='grid gap-5 md:grid-cols-2'>",
    "        {items.length === 0 ? <p>Sin herramientas.</p> : items.map((t:any) => (",
    "        <Card key={t.name}><Badge tone={t.requires_approval ? 'warning' : 'success'}>{t.requires_approval ? 'Requiere HIL' : 'Libre'}</Badge>",
    "            <h3 className='mt-3 text-lg font-black'>{t.name}</h3>",
    "            <p className='mt-2 text-sm text-brand-muted'>{t.description}</p>",
    "        </Card>",
    "        ))}",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "export function MessagesView() {",
    "  const [items, setItems] = useState<any[]>([]);",
    "  const [projects, setProjects] = useState<any[]>([]);",
    "  const [projectId, setProjectId] = useState<string>('');",
    "  useEffect(() => { projectsRepository.list().then(p => { setProjects(p); if(p.length > 0) setProjectId(p[0].id); }); }, []);",
    "  useEffect(() => { if(projectId) futureRepository.messages(projectId).then(setItems); }, [projectId]);",
    "  return (",
    "    <div><SectionHeader title='Mensajes' description='Historial por proyecto.' />",
    "      <ProjectSelector projects={projects} projectId={projectId} setProjectId={setProjectId} />",
    "      <div className='space-y-4'>",
    "        {items.length === 0 ? <p>Sin mensajes.</p> : items.map((m:any) => (",
    "        <Card key={m.id}><Badge tone={m.remitente === 'user' ? 'info' : 'success'}>{m.remitente}</Badge>",
    "            <p className='mt-3 text-sm text-brand-navy whitespace-pre-wrap'>{m.contenido}</p>",
    "        </Card>",
    "        ))}",
    "      </div>",
    "    </div>",
    "  );",
    "}"
])

# 6. FIX FRONTEND PROJECT DETAIL: Editar Descripción y Borrar Proyecto
w("frontend/features/projects/ProjectDetailView.tsx", [
    "\"use client\";",
    "import Link from 'next/link';",
    "import { useEffect, useState } from 'react';",
    "import { useRouter } from 'next/navigation';",
    "import { Badge } from '@/components/ui/Badge';",
    "import { Button } from '@/components/ui/Button';",
    "import { Card, CardTitle } from '@/components/ui/Card';",
    "import { SectionHeader } from '@/components/ui/SectionHeader';",
    "import { projectsRepository, futureRepository } from '@/services/repositories';",
    "export function ProjectDetailView({ projectId }: { projectId: string }) {",
    "  const [project, setProject] = useState<any>(null);",
    "  const [readme, setReadme] = useState('');",
    "  const [editReadme, setEditReadme] = useState(false);",
    "  const [tempReadme, setTempReadme] = useState('');",
    "  const [editDesc, setEditDesc] = useState(false);",
    "  const [tempDesc, setTempDesc] = useState('');",
    "  const [editRole, setEditRole] = useState<string | null>(null);",
    "  const [tempRole, setTempRole] = useState('');",
    "  const router = useRouter();",
    "  const loadData = async () => {",
    "      const p = await projectsRepository.get(projectId);",
    "      setProject(p); setTempDesc(p.descripcion);",
    "      const r = await futureRepository.readme(projectId);",
    "      setReadme(r?.content || 'No hay README');",
    "  };",
    "  useEffect(() => { loadData(); }, [projectId]);",
    "  const saveRole = async (key: string) => {",
    "    await projectsRepository.patch(projectId, { [key]: tempRole });",
    "    setProject({...project, [key]: tempRole});",
    "    setEditRole(null);",
    "  };",
    "  const saveDesc = async () => {",
    "    await projectsRepository.patch(projectId, { descripcion: tempDesc });",
    "    setProject({...project, descripcion: tempDesc});",
    "    setEditDesc(false);",
    "  };",
    "  const saveReadme = async () => {",
    "    await futureRepository.updateReadme(projectId, tempReadme);",
    "    setReadme(tempReadme);",
    "    setEditReadme(false);",
    "  };",
    "  const handleDelete = async () => {",
    "    if(confirm('¿Eliminar proyecto DEFINITIVAMENTE (Workspace y Repo en GitHub)?')) {",
    "      await projectsRepository.delete(projectId);",
    "      router.push('/projects');",
    "    }",
    "  };",
    "  if (!project) return <p>Cargando...</p>;",
    "  return (",
    "    <div>",
    "      <SectionHeader title={project.titulo} description={project.descripcion.substring(0,50)+'...'} action={<div className='flex gap-2'><Button variant='secondary' onClick={handleDelete}>Borrar</Button><Link href={`/chat/${project.id}`}><Button>Abrir Chat</Button></Link></div>} />",
    "      <div className='grid gap-6 xl:grid-cols-[1.1fr_.9fr]'>",
    "        <div className='space-y-6'>",
    "          <Card>",
    "            <div className='flex justify-between items-center mb-4'>",
    "              <CardTitle eyebrow='Contexto' title='Descripción' />",
    "              <Button variant='secondary' onClick={() => setEditDesc(!editDesc)}>{editDesc ? 'Cancelar' : 'Editar'}</Button>",
    "            </div>",
    "            {editDesc ? (",
    "              <div className='space-y-3'>",
    "                <textarea className='w-full min-h-[100px] p-2 border rounded-xl text-sm' value={tempDesc} onChange={e => setTempDesc(e.target.value)} />",
    "                <Button onClick={saveDesc}>Guardar</Button>",
    "              </div>",
    "            ) : (",
    "              <p className='text-sm text-brand-muted'>{project.descripcion}</p>",
    "            )}",
    "          </Card>",
    "          <Card>",
    "            <div className='flex justify-between items-center mb-4'>",
    "              <CardTitle eyebrow={project.nombre_slug} title='README.md' />",
    "              <Button variant='secondary' onClick={() => { setTempReadme(readme); setEditReadme(!editReadme); }}>{editReadme ? 'Cancelar' : 'Editar'}</Button>",
    "            </div>",
    "            {editReadme ? (",
    "              <div className='space-y-3'>",
    "                <textarea className='w-full min-h-[300px] p-4 bg-brand-deep text-brand-bright font-mono text-xs rounded-xl' value={tempReadme} onChange={e => setTempReadme(e.target.value)} />",
    "                <Button onClick={saveReadme}>Guardar</Button>",
    "              </div>",
    "            ) : (",
    "              <pre className='p-4 bg-brand-soft rounded-xl text-sm whitespace-pre-wrap'>{readme}</pre>",
    "            )}",
    "          </Card>",
    "        </div>",
    "        <div className='space-y-6'>",
    "          <Card>",
    "            <div className='flex justify-between'><CardTitle eyebrow='Metadata' title='Detalles' /></div>",
    "            <p className='text-xs mt-2'><b>Responsable:</b> {project.responsable || 'N/A'}</p>",
    "            <p className='text-xs'><b>Año:</b> {project.anio}</p>",
    "            <p className='text-xs'><b>Estado:</b> {project.estado}</p>",
    "          </Card>",
    "          <Card>",
    "            <CardTitle eyebrow='Roles' title='Sala multi-agente' />",
    "            <div className='space-y-4 mt-4'>",
    "              {[['rol_gemini', 'Gemini · Infra'], ['rol_chatgpt', 'ChatGPT · Backend'], ['rol_claude', 'Claude · Frontend']].map(([key, label]) => (",
    "                <div key={key} className='p-3 border border-brand-border rounded-xl bg-brand-soft'>",
    "                  <div className='flex justify-between items-center'>",
    "                    <span className='font-bold text-sm text-brand-navy'>{label}</span>",
    "                    <button className='text-brand-cyan text-xs font-black uppercase' onClick={() => { setEditRole(key); setTempRole(project[key]); }}>Editar</button>",
    "                  </div>",
    "                  {editRole === key ? (",
    "                    <div className='mt-3 flex flex-col gap-2'>",
    "                      <textarea className='w-full text-xs p-2 border rounded-xl h-20' value={tempRole} onChange={e => setTempRole(e.target.value)} />",
    "                      <Button onClick={() => saveRole(key)}>Guardar Rol</Button>",
    "                    </div>",
    "                  ) : (",
    "                    <p className='text-xs text-brand-muted mt-2'>{project[key]}</p>",
    "                  )}",
    "                </div>",
    "              ))}",
    "            </div>",
    "          </Card>",
    "        </div>",
    "      </div>",
    "    </div>",
    "  );",
    "}"
])

# 7. FIX FRONTEND: Selector Público/Privado en el Formulario de Nuevo Proyecto
w("frontend/features/projects/ProjectForm.tsx", [
    "\"use client\";",
    "import { useState } from 'react';",
    "import { useRouter } from 'next/navigation';",
    "import { Button } from '@/components/ui/Button';",
    "import { Input } from '@/components/ui/Input';",
    "import { SectionHeader } from '@/components/ui/SectionHeader';",
    "import { projectsRepository } from '@/services/repositories';",
    "export function ProjectForm() {",
    "  const router = useRouter();",
    "  const [form, setForm] = useState({ titulo: '', responsable: '', descripcion: '', github_url: '', anio: new Date().getFullYear(), rol_gemini: 'Experto Infra, FullStack', rol_chatgpt: 'Experto Backend y Datos', rol_claude: 'Experto Frontend y UX', estado: 'privado' });",
    "  const submit = async (e: any) => {",
    "    e.preventDefault();",
    "    const p = await projectsRepository.create(form);",
    "    if(p && p.id) router.push(`/projects/${p.id}`);",
    "  };",
    "  return (",
    "    <form onSubmit={submit} className='max-w-2xl space-y-6'>",
    "      <SectionHeader title='Crear proyecto' description='Registra una nueva iniciativa.' />",
    "      <div className='p-6 bg-white rounded-3xl shadow-sm border space-y-4'>",
    "        <h3 className='font-black text-brand-navy'>Datos base</h3>",
    "        <Input label='Título' value={form.titulo} onChange={e => setForm({...form, titulo: e.target.value})} required />",
    "        <Input label='Responsable' value={form.responsable} onChange={e => setForm({...form, responsable: e.target.value})} required />",
    "        <div><label className='block text-xs font-bold text-brand-muted uppercase mb-1'>Descripción</label><textarea className='w-full border rounded-xl p-3 text-sm min-h-[100px]' value={form.descripcion} onChange={e => setForm({...form, descripcion: e.target.value})} required /></div>",
    "        <div className='grid grid-cols-2 gap-4'>",
    "          <Input label='GitHub URL' value={form.github_url} onChange={e => setForm({...form, github_url: e.target.value})} />",
    "          <div>",
    "            <label className='block text-xs font-bold text-brand-muted uppercase mb-1'>Privacidad GitOps</label>",
    "            <select className='w-full border rounded-xl p-3 text-sm' value={form.estado} onChange={e => setForm({...form, estado: e.target.value})}>",
    "              <option value='privado'>Privado</option>",
    "              <option value='publico'>Público</option>",
    "            </select>",
    "          </div>",
    "        </div>",
    "        <h3 className='font-black text-brand-navy mt-6'>Roles Multi-Agente</h3>",
    "        <Input label='Rol Gemini' value={form.rol_gemini} onChange={e => setForm({...form, rol_gemini: e.target.value})} />",
    "        <Input label='Rol ChatGPT' value={form.rol_chatgpt} onChange={e => setForm({...form, rol_chatgpt: e.target.value})} />",
    "        <Input label='Rol Claude' value={form.rol_claude} onChange={e => setForm({...form, rol_claude: e.target.value})} />",
    "        <Button type='submit' className='w-full mt-4'>Crear proyecto</Button>",
    "      </div>",
    "    </form>",
    "  );",
    "}"
])

print("✅ Operación finalizada")
