import os

def w(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"✅ Actualizado: {path}")

def deploy():
    print("🚀 INICIANDO MEGA-PARCHE ENTERPRISE...")

    # 1. GITHUB ROUTER (Fix Author Identity)
    w("backend/app/routers/github.py", [
        "import subprocess",
        "from uuid import UUID",
        "from fastapi import APIRouter, Depends",
        "from sqlalchemy.ext.asyncio import AsyncSession",
        "from app.database import get_db",
        "from app.config import get_settings",
        "from app.models import Proyecto",
        "router = APIRouter()",
        "settings = get_settings()",
        "async def get_cwd(project_id: str, db: AsyncSession):",
        "    p = await db.get(Proyecto, UUID(project_id))",
        "    path = settings.base_projects_dir / p.nombre_slug",
        "    path.mkdir(parents=True, exist_ok=True)",
        "    return str(path)",
        "@router.post('/{project_id}/status')",
        "async def git_status(project_id: str, db: AsyncSession = Depends(get_db)):",
        "    cwd = await get_cwd(project_id, db)",
        "    subprocess.run(['git', 'init'], cwd=cwd, capture_output=True)",
        "    res = subprocess.run(['git', 'status'], cwd=cwd, capture_output=True, text=True)",
        "    return {'output': res.stdout or res.stderr}",
        "@router.post('/{project_id}/add')",
        "async def git_add(project_id: str, db: AsyncSession = Depends(get_db)):",
        "    cwd = await get_cwd(project_id, db)",
        "    res = subprocess.run(['git', 'add', '.'], cwd=cwd, capture_output=True, text=True)",
        "    return {'output': 'Agregado al staging.\\n' + (res.stdout or res.stderr)}",
        "@router.post('/{project_id}/commit')",
        "async def git_commit(project_id: str, db: AsyncSession = Depends(get_db)):",
        "    cwd = await get_cwd(project_id, db)",
        "    subprocess.run(['git', 'config', 'user.email', 'bot@nodara.local'], cwd=cwd)",
        "    subprocess.run(['git', 'config', 'user.name', 'Nodara Bot'], cwd=cwd)",
        "    res = subprocess.run(['git', 'commit', '-m', 'Version via Nodara'], cwd=cwd, capture_output=True, text=True)",
        "    return {'output': res.stdout or res.stderr}",
        "@router.post('/{project_id}/push')",
        "async def git_push(project_id: str, db: AsyncSession = Depends(get_db)):",
        "    cwd = await get_cwd(project_id, db)",
        "    res = subprocess.run(['git', 'push'], cwd=cwd, capture_output=True, text=True)",
        "    out = res.stdout or res.stderr",
        "    if not out: out = 'Error: Upstream no configurado o sin origin.'",
        "    return {'output': out}"
    ])

    # 2. CONFIG ROUTER (Fix GitHub API Key visibility)
    w("backend/app/routers/config.py", [
        "from fastapi import APIRouter, Depends",
        "from sqlalchemy import select",
        "from sqlalchemy.ext.asyncio import AsyncSession",
        "from app.database import get_db",
        "from app.config import get_settings",
        "router = APIRouter()",
        "settings = get_settings()",
        "@router.get('')",
        "async def get_config(db: AsyncSession = Depends(get_db)):",
        "    from app.models.governance import UsuarioConfig",
        "    res = await db.execute(select(UsuarioConfig))",
        "    cfg = res.scalars().first()",
        "    return [{",
        "        'id': cfg.id if cfg else 1,",
        "        'auto_aprobar_ejecucion': cfg.auto_aprobar_ejecucion if cfg else False,",
        "        'saldo_virtual_openai': float(cfg.saldo_virtual_openai) if cfg and cfg.saldo_virtual_openai else 0.0,",
        "        'saldo_virtual_anthropic': float(cfg.saldo_virtual_anthropic) if cfg and cfg.saldo_virtual_anthropic else 0.0,",
        "        'saldo_virtual_gemini': float(cfg.saldo_virtual_gemini) if cfg and cfg.saldo_virtual_gemini else 0.0,",
        "        'has_api_key_github': bool(settings.github_personal_access_token),",
        "        'has_api_key_openai': bool(settings.openai_api_key),",
        "        'has_api_key_anthropic': bool(settings.anthropic_api_key),",
        "        'has_api_key_gemini': bool(settings.gemini_api_key)",
        "    }]",
        "@router.patch('/{config_id}')",
        "async def update_config(config_id: int, payload: dict, db: AsyncSession = Depends(get_db)):",
        "    from app.models.governance import UsuarioConfig",
        "    cfg = await db.get(UsuarioConfig, config_id)",
        "    if not cfg:",
        "        cfg = UsuarioConfig(id=config_id)",
        "        db.add(cfg)",
        "    for k, v in payload.items():",
        "        if hasattr(cfg, k): setattr(cfg, k, v)",
        "    await db.commit()",
        "    await db.refresh(cfg)",
        "    return {'status': 'ok'}"
    ])

    # 3. METRICS ROUTER (Fix counts)
    w("backend/app/routers/metrics.py", [
        "from fastapi import APIRouter, Depends",
        "from sqlalchemy import select, func",
        "from sqlalchemy.ext.asyncio import AsyncSession",
        "from app.database import get_db",
        "router = APIRouter()",
        "@router.get('')",
        "async def get_metrics(db: AsyncSession = Depends(get_db)):",
        "    from app.models import Proyecto",
        "    total = await db.execute(select(func.count(Proyecto.id)))",
        "    act = await db.execute(select(func.count(Proyecto.id)).where(Proyecto.estado == 'activo'))",
        "    inact = await db.execute(select(func.count(Proyecto.id)).where(Proyecto.estado != 'activo'))",
        "    return [",
        "        {'label': 'Proyectos Totales', 'value': str(total.scalar() or 0), 'tone': 'info', 'trend': 'global'},",
        "        {'label': 'Proyectos Activos', 'value': str(act.scalar() or 0), 'tone': 'success', 'trend': 'en curso'},",
        "        {'label': 'Proyectos Inactivos', 'value': str(inact.scalar() or 0), 'tone': 'warning', 'trend': 'pausados'}",
        "    ]"
    ])

    # 4. FRONTEND: PROJECT DETAIL
    w("frontend/features/projects/ProjectDetailView.tsx", [
        "\"use client\";",
        "import Link from 'next/link';",
        "import { useEffect, useState } from 'react';",
        "import { useRouter } from 'next/navigation';",
        "import { Badge } from '@/components/ui/Badge';",
        "import { Button } from '@/components/ui/Button';",
        "import { Card, CardTitle } from '@/components/ui/Card';",
        "import { SectionHeader } from '@/components/ui/SectionHeader';",
        "import { projectsRepository, futureRepository } from '@/services/repositories';",
        "export function ProjectDetailView({ projectId }: { projectId: string }) {",
        "  const [project, setProject] = useState<any>(null);",
        "  const [readme, setReadme] = useState('');",
        "  const [editReadme, setEditReadme] = useState(false);",
        "  const [tempReadme, setTempReadme] = useState('');",
        "  const [editRole, setEditRole] = useState<string | null>(null);",
        "  const [tempRole, setTempRole] = useState('');",
        "  const loadData = async () => {",
        "      const p = await projectsRepository.get(projectId);",
        "      setProject(p);",
        "      const r = await futureRepository.readme(projectId);",
        "      setReadme(r?.content || 'No hay README');",
        "  };",
        "  useEffect(() => { loadData(); }, [projectId]);",
        "  const saveRole = async (key: string) => {",
        "    await projectsRepository.patch(projectId, { [key]: tempRole });",
        "    setProject((prev: any) => prev ? {...prev, [key]: tempRole} : null);",
        "    setEditRole(null);",
        "  };",
        "  const saveReadme = async () => {",
        "    await futureRepository.updateReadme(projectId, tempReadme);",
        "    setReadme(tempReadme);",
        "    setEditReadme(false);",
        "  };",
        "  if (!project) return <p>Cargando...</p>;",
        "  return (",
        "    <div>",
        "      <SectionHeader title={project.titulo} description={project.descripcion} action={<Link href={`/chat/${project.id}`}><Button>Abrir Chat</Button></Link>} />",
        "      <div className='grid gap-6 xl:grid-cols-[1.1fr_.9fr]'>",
        "        <div className='space-y-6'>",
        "          <Card>",
        "            <div className='flex justify-between items-center mb-4'>",
        "              <CardTitle eyebrow={project.nombre_slug} title='README.md' />",
        "              <Button variant='secondary' onClick={() => { setTempReadme(readme); setEditReadme(!editReadme); }}>{editReadme ? 'Cancelar' : 'Editar'}</Button>",
        "            </div>",
        "            {editReadme ? (",
        "              <div className='space-y-3'>",
        "                <textarea className='w-full min-h-[300px] p-4 bg-brand-deep text-brand-bright font-mono text-xs rounded-xl' value={tempReadme} onChange={e => setTempReadme(e.target.value)} />",
        "                <Button onClick={saveReadme}>Guardar</Button>",
        "              </div>",
        "            ) : (",
        "              <pre className='p-4 bg-brand-soft rounded-xl text-sm whitespace-pre-wrap'>{readme}</pre>",
        "            )}",
        "          </Card>",
        "          <Card>",
        "             <CardTitle eyebrow='Metadata' title='Detalles' />",
        "             <pre className='mt-5 overflow-auto rounded-3xl bg-brand-deep p-5 text-xs leading-6 text-brand-bright'>{JSON.stringify({ tecnologias: project.tecnologias, microservicios: project.microservicios }, null, 2)}</pre>",
        "          </Card>",
        "        </div>",
        "        <Card>",
        "          <CardTitle eyebrow='Roles' title='Sala multi-agente' />",
        "          <div className='space-y-4 mt-4'>",
        "            {[['rol_gemini', 'Gemini · Infra'], ['rol_chatgpt', 'ChatGPT · Backend'], ['rol_claude', 'Claude · Frontend']].map(([key, label]) => (",
        "              <div key={key} className='p-3 border border-brand-border rounded-xl bg-brand-soft'>",
        "                <div className='flex justify-between items-center'>",
        "                  <span className='font-bold text-sm text-brand-navy'>{label}</span>",
        "                  <button className='text-brand-cyan text-xs font-black uppercase' onClick={() => { setEditRole(key); setTempRole(project[key]); }}>Editar</button>",
        "                </div>",
        "                {editRole === key ? (",
        "                  <div className='mt-3 flex flex-col gap-2'>",
        "                    <textarea className='w-full text-xs p-2 border rounded-xl h-20' value={tempRole} onChange={e => setTempRole(e.target.value)} />",
        "                    <Button onClick={() => saveRole(key)}>Guardar Rol</Button>",
        "                  </div>",
        "                ) : (",
        "                  <p className='text-xs text-brand-muted mt-2'>{project[key]}</p>",
        "                )}",
        "              </div>",
        "            ))}",
        "          </div>",
        "        </Card>",
        "      </div>",
        "    </div>",
        "  );",
        "}"
    ])

    # 5. FRONTEND: FUTURE TABLES (Agents, Workspace, Metrics, GitHub)
    w("frontend/features/future/FutureTables.tsx", [
        "\"use client\";",
        "import { useEffect, useState } from 'react';",
        "import { Badge } from '@/components/ui/Badge';",
        "import { Button } from '@/components/ui/Button';",
        "import { Card, CardTitle } from '@/components/ui/Card';",
        "import { SectionHeader } from '@/components/ui/SectionHeader';",
        "import { futureRepository, projectsRepository, githubRepository } from '@/services/repositories';",
        "function ProjectSelector({ projects, projectId, setProjectId }: any) {",
        "    if (projects.length === 0) return null;",
        "    return (",
        "        <div className='mb-6'>",
        "            <label className='mr-4 font-bold text-sm'>Seleccionar Proyecto:</label>",
        "            <select className='border border-brand-border bg-white p-2 rounded-xl text-sm' value={projectId} onChange={(e) => setProjectId(e.target.value)}>",
        "                {projects.map((p:any) => <option key={p.id} value={p.id}>{p.titulo}</option>)}",
        "            </select>",
        "        </div>",
        "    );",
        "}",
        "export function AgentsView() {",
        "  const [projects, setProjects] = useState<any[]>([]);",
        "  const [projectId, setProjectId] = useState<string>('');",
        "  const [project, setProject] = useState<any>(null);",
        "  useEffect(() => { projectsRepository.list().then(p => { setProjects(p); if(p.length > 0) setProjectId(p[0].id); }); }, []);",
        "  useEffect(() => { if(projectId) projectsRepository.get(projectId).then(setProject); }, [projectId]);",
        "  return (",
        "    <div>",
        "      <SectionHeader title='Gestión de agentes' description='Roles activos según el proyecto seleccionado.' />",
        "      <ProjectSelector projects={projects} projectId={projectId} setProjectId={setProjectId} />",
        "      {project && (",
        "        <div className='grid gap-5 xl:grid-cols-3'>",
        "          <Card><Badge tone='success'>Gemini</Badge><h3 className='mt-3 font-black text-xl'>Infraestructura</h3><p className='mt-2 text-sm text-brand-muted'>{project.rol_gemini}</p></Card>",
        "          <Card><Badge tone='success'>ChatGPT</Badge><h3 className='mt-3 font-black text-xl'>Backend y Datos</h3><p className='mt-2 text-sm text-brand-muted'>{project.rol_chatgpt}</p></Card>",
        "          <Card><Badge tone='success'>Claude</Badge><h3 className='mt-3 font-black text-xl'>Frontend y UX</h3><p className='mt-2 text-sm text-brand-muted'>{project.rol_claude}</p></Card>",
        "        </div>",
        "      )}",
        "    </div>",
        "  );",
        "}",
        "function Tree({ nodes, depth = 0, onFileClick }: any) {",
        "  return (",
        "    <div className='space-y-1 mt-2'>",
        "      {nodes.map((node: any) => (",
        "        <div key={node.id} style={{ marginLeft: depth * 20 }}>",
        "          <div className={`px-2 py-1 text-sm rounded ${node.type === 'file' ? 'cursor-pointer hover:bg-brand-soft text-brand-cyan' : 'font-bold text-brand-navy'}`} onClick={() => node.type === 'file' && onFileClick(node.path)}>",
        "            {node.type === 'folder' ? '📁' : '📄'} {node.name}",
        "          </div>",
        "          {node.children && <Tree nodes={node.children} depth={depth + 1} onFileClick={onFileClick} />}",
        "        </div>",
        "      ))}",
        "    </div>",
        "  );",
        "}",
        "export function WorkspaceView() {",
        "  const [items, setItems] = useState<any[]>([]);",
        "  const [projects, setProjects] = useState<any[]>([]);",
        "  const [projectId, setProjectId] = useState<string>('');",
        "  const [fileContent, setFileContent] = useState<string>('');",
        "  useEffect(() => { projectsRepository.list().then(p => { setProjects(p); if(p.length > 0) setProjectId(p[0].id); }); }, []);",
        "  useEffect(() => { if (projectId) { futureRepository.workspace(projectId).then(setItems); setFileContent(''); } }, [projectId]);",
        "  const handleFileClick = async (path: string) => {",
        "      const res = await futureRepository.workspaceFile(projectId, path);",
        "      setFileContent(res?.content || 'No se pudo leer el archivo.');",
        "  };",
        "  return (",
        "    <div>",
        "      <SectionHeader title='Workspace' description='Haz clic en un archivo para visualizarlo.' />",
        "      <ProjectSelector projects={projects} projectId={projectId} setProjectId={setProjectId} />",
        "      <div className='grid xl:grid-cols-[300px_1fr] gap-6'>",
        "        <Card>",
        "          <CardTitle title='Explorador' />",
        "          <Tree nodes={items} onFileClick={handleFileClick} />",
        "        </Card>",
        "        <Card>",
        "           <CardTitle title='Visualizador' />",
        "           <pre className='mt-4 p-4 bg-brand-deep text-brand-bright text-xs rounded-xl overflow-auto max-h-[600px]'>{fileContent || 'Selecciona un archivo del explorador.'}</pre>",
        "        </Card>",
        "      </div>",
        "    </div>",
        "  );",
        "}",
        "export function GithubView() {",
        "  const [projects, setProjects] = useState<any[]>([]);",
        "  const [projectId, setProjectId] = useState<string>('');",
        "  const [output, setOutput] = useState<string>('');",
        "  useEffect(() => { projectsRepository.list().then(p => { setProjects(p); if(p.length > 0) setProjectId(p[0].id); }); }, []);",
        "  const runCmd = async (action: 'status' | 'add' | 'commit' | 'push') => {",
        "      setOutput('Ejecutando...');",
        "      try {",
        "          const res = await githubRepository[action](projectId);",
        "          setOutput(res?.output || 'Comando ejecutado con éxito.');",
        "      } catch (e) { setOutput('Error ejecutando el comando.'); }",
        "  };",
        "  return (",
        "    <div>",
        "      <SectionHeader title='GitOps' description='Control de versiones.' />",
        "      <ProjectSelector projects={projects} projectId={projectId} setProjectId={setProjectId} />",
        "      <Card>",
        "        <div className='flex gap-2 mb-4'>",
        "            <Button variant='secondary' onClick={() => runCmd('status')}>Git Status</Button>",
        "            <Button variant='secondary' onClick={() => runCmd('add')}>Git Add</Button>",
        "            <Button variant='secondary' onClick={() => runCmd('commit')}>Git Commit</Button>",
        "            <Button onClick={() => runCmd('push')}>Git Push</Button>",
        "        </div>",
        "        <pre className='bg-brand-deep text-brand-bright p-4 rounded-xl text-sm whitespace-pre-wrap'>{output}</pre>",
        "      </Card>",
        "    </div>",
        "  );",
        "}",
        "export function MetricsView() {",
        "  const [items, setItems] = useState<any[]>([]);",
        "  useEffect(() => { futureRepository.metrics().then(setItems); }, []);",
        "  return (",
        "    <div>",
        "      <SectionHeader title='Métricas' description='Dashboard.' />",
        "      <div className='grid gap-5 md:grid-cols-3'>",
        "        {items.map((m, i) => (",
        "        <Card key={i}>",
        "            <p className='text-sm font-bold text-brand-muted'>{m.label}</p>",
        "            <p className='mt-3 text-3xl font-black'>{m.value}</p>",
        "            <Badge tone={m.tone} className='mt-4'>{m.trend}</Badge>",
        "        </Card>",
        "        ))}",
        "      </div>",
        "    </div>",
        "  );",
        "}",
        "export function AuditView() { return <div><SectionHeader title='Auditoría' description='Logs' /></div>; }",
        "export function ToolsView() { return <div><SectionHeader title='Tools' description='Catálogo' /></div>; }",
        "export function MessagesView() { return <div><SectionHeader title='Mensajes' description='Historial' /></div>; }"
    ])

    # 6. FRONTEND: CHAT (Subida de archivos)
    w("frontend/features/chat/MultiAgentChat.tsx", [
        "\"use client\";",
        "import { useEffect, useRef, useState } from 'react';",
        "import { Badge } from '@/components/ui/Badge';",
        "import { Button } from '@/components/ui/Button';",
        "import { Card, CardTitle } from '@/components/ui/Card';",
        "import { SectionHeader } from '@/components/ui/SectionHeader';",
        "import { WS_BASE_URL } from '@/lib/env';",
        "import { filesRepository } from '@/services/repositories';",
        "export function MultiAgentChat({ projectId }: { projectId: string }) {",
        "  const [input, setInput] = useState('');",
        "  const [events, setEvents] = useState<any[]>([]);",
        "  const [status, setStatus] = useState('closed');",
        "  const wsRef = useRef<WebSocket | null>(null);",
        "  useEffect(() => {",
        "    const wsUrl = `${WS_BASE_URL}/ws/chat/${projectId}?usuario_config_id=1`;",
        "    const socket = new WebSocket(wsUrl);",
        "    wsRef.current = socket;",
        "    socket.onopen = () => setStatus('open');",
        "    socket.onclose = () => setStatus('closed');",
        "    socket.onmessage = (event) => {",
        "      try {",
        "        const raw = JSON.parse(event.data);",
        "        setEvents(prev => [...prev, { type: raw.event, agent: raw.data?.agent, message: raw.data?.message }]);",
        "      } catch {}",
        "    };",
        "    return () => socket.close();",
        "  }, [projectId]);",
        "  function send() {",
        "    if (!input.trim() || !wsRef.current) return;",
        "    wsRef.current.send(JSON.stringify({ message: input, correlation_id: crypto.randomUUID() }));",
        "    setInput('');",
        "  }",
        "  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {",
        "    const file = e.target.files?.[0];",
        "    if(!file) return;",
        "    try {",
        "      await filesRepository.upload(projectId, file);",
        "      setInput(`[Archivo Subido: ${file.name}] Por favor analízalo.`);",
        "    } catch(err) {",
        "      console.error('Error subiendo archivo', err);",
        "    }",
        "  };",
        "  return (",
        "    <div className='grid gap-6 xl:grid-cols-[1fr_300px]'>",
        "      <Card className='min-h-[600px] flex flex-col'>",
        "        <CardTitle eyebrow='Conversación' title='Sala de orquestación' action={<Badge>{status}</Badge>} />",
        "        <div className='flex-1 overflow-y-auto bg-brand-soft rounded-2xl p-4 mt-4 space-y-4'>",
        "          {events.map((e, i) => (",
        "            <div key={i} className='bg-white p-3 rounded-xl shadow-sm'>",
        "              <span className='font-bold text-xs text-brand-cyan uppercase'>{e.type}</span>",
        "              {e.agent && <span className='ml-2 text-xs font-bold text-brand-navy'>[{e.agent}]</span>}",
        "              <p className='mt-2 text-sm whitespace-pre-wrap'>{e.message}</p>",
        "            </div>",
        "          ))}",
        "        </div>",
        "        <div className='mt-4 flex gap-2 items-center'>",
        "          <label className='cursor-pointer bg-brand-soft px-4 py-3 rounded-2xl border text-sm font-bold hover:bg-brand-border transition'>",
        "            📎 Subir",
        "            <input type='file' className='hidden' onChange={handleFileUpload} />",
        "          </label>",
        "          <input className='flex-1 rounded-2xl border px-4 py-3' placeholder='gemini: comando...' value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && send()} />",
        "          <Button onClick={send}>Enviar</Button>",
        "        </div>",
        "      </Card>",
        "    </div>",
        "  );",
        "}"
    ])

    print("\n✅ ¡Todos los archivos han sido actualizados con éxito!")
    print("👉 Ejecuta ahora: docker compose restart backend frontend")

if __name__ == "__main__":
    deploy()