import os

def w(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"✅ Reparado: {path}")

def fix():
    print("🚀 INICIANDO REPARACIÓN ARQUITECTÓNICA COMPLETA...")

    # 1. ROUTER PROJECTS: Orden de rutas corregido para evitar 404s en /readme, /messages, /workspace
    w("backend/app/routers/projects.py", [
        "import os, subprocess",
        "from uuid import UUID",
        "from pathlib import Path",
        "from fastapi import APIRouter, Depends, HTTPException",
        "from sqlalchemy import select",
        "from sqlalchemy.ext.asyncio import AsyncSession",
        "from pydantic import BaseModel",
        "from app.database import get_db",
        "from app.config import get_settings",
        "from app.schemas import ProyectoCreate, ProyectoOut, ProyectoUpdate",
        "from app.services.slug import slugify",
        "router = APIRouter()",
        "settings = get_settings()",
        "class ReadmeUpdate(BaseModel): content: str",
        "@router.get('', response_model=list[ProyectoOut])",
        "async def list_projects(db: AsyncSession = Depends(get_db)):",
        "    from app.models import Proyecto",
        "    res = await db.execute(select(Proyecto).order_by(Proyecto.fecha_creacion.desc()))",
        "    return list(res.scalars().all())",
        "@router.post('', response_model=ProyectoOut)",
        "async def create_project(payload: ProyectoCreate, db: AsyncSession = Depends(get_db)):",
        "    from app.models import Proyecto",
        "    slug = payload.nombre_slug or slugify(payload.titulo)",
        "    obj = Proyecto(**payload.model_dump(exclude={'nombre_slug'}), nombre_slug=slug)",
        "    db.add(obj)",
        "    await db.commit()",
        "    await db.refresh(obj)",
        "    try:",
        "        ws = settings.base_projects_dir / obj.nombre_slug",
        "        ws.mkdir(parents=True, exist_ok=True)",
        "        subprocess.run('chmod -R 777 ' + str(ws), shell=True)",
        "        with open(ws / 'README.md', 'w', encoding='utf-8') as f:",
        "            f.write('# ' + obj.titulo + '\\n\\n' + obj.descripcion)",
        "    except: pass",
        "    return obj",
        "# --- RUTAS ESPECÍFICAS PRIMERO (FIX 404) ---",
        "@router.get('/{project_id}/readme')",
        "async def get_readme(project_id: str, db: AsyncSession = Depends(get_db)):",
        "    from app.models import Proyecto",
        "    p = await db.get(Proyecto, UUID(project_id))",
        "    path = settings.base_projects_dir / p.nombre_slug / 'README.md'",
        "    if path.exists():",
        "        with open(path, 'r', encoding='utf-8') as f: return {'content': f.read()}",
        "    return {'content': 'Sin README.'}",
        "@router.patch('/{project_id}/readme')",
        "async def update_readme(project_id: str, payload: ReadmeUpdate, db: AsyncSession = Depends(get_db)):",
        "    from app.models import Proyecto",
        "    p = await db.get(Proyecto, UUID(project_id))",
        "    ws = settings.base_projects_dir / p.nombre_slug",
        "    with open(ws / 'README.md', 'w', encoding='utf-8') as f: f.write(payload.content)",
        "    return {'status': 'ok'}",
        "@router.get('/{project_id}/workspace/file')",
        "async def read_file(project_id: str, file_path: str, db: AsyncSession = Depends(get_db)):",
        "    from app.models import Proyecto",
        "    p = await db.get(Proyecto, UUID(project_id))",
        "    base = str(settings.base_projects_dir / p.nombre_slug)",
        "    if file_path.startswith(base): fp = Path(file_path)",
        "    else: fp = settings.base_projects_dir / p.nombre_slug / file_path.lstrip('./').lstrip('/')",
        "    if not fp.is_file(): raise HTTPException(404, 'No encontrado')",
        "    with open(fp, 'r', encoding='utf-8', errors='replace') as f: return {'content': f.read()}",
        "@router.get('/{project_id}/workspace/tree')",
        "async def get_tree(project_id: str, db: AsyncSession = Depends(get_db)):",
        "    from app.models import Proyecto",
        "    p = await db.get(Proyecto, UUID(project_id))",
        "    b = settings.base_projects_dir / p.nombre_slug",
        "    if not b.exists(): return []",
        "    def bt(path):",
        "        n = os.path.basename(path)",
        "        if os.path.isdir(path):",
        "            return {'id': path, 'name': n, 'type': 'folder', 'path': path, 'children': [bt(os.path.join(path, x)) for x in os.listdir(path) if not x.startswith('.git')]}",
        "        return {'id': path, 'name': n, 'type': 'file', 'path': path}",
        "    return [bt(os.path.join(b, x)) for x in os.listdir(b) if not x.startswith('.git')]",
        "@router.get('/{project_id}/messages')",
        "async def get_msgs(project_id: str, db: AsyncSession = Depends(get_db)):",
        "    from app.models.history_models import MensajeHistorial",
        "    try:",
        "        r = await db.execute(select(MensajeHistorial).where(MensajeHistorial.proyecto_id == UUID(project_id)).order_by(MensajeHistorial.fecha_envio.asc()))",
        "        return list(r.scalars().all())",
        "    except: return []",
        "# --- RUTAS GENÉRICAS AL FINAL ---",
        "@router.get('/{project_id}', response_model=ProyectoOut)",
        "async def get_project(project_id: str, db: AsyncSession = Depends(get_db)):",
        "    from app.models import Proyecto",
        "    try: p_id = UUID(project_id)",
        "    except: raise HTTPException(400, 'UUID invalido')",
        "    obj = await db.get(Proyecto, p_id)",
        "    if not obj: raise HTTPException(404)",
        "    return obj",
        "@router.patch('/{project_id}', response_model=ProyectoOut)",
        "async def update_project(project_id: str, payload: dict, db: AsyncSession = Depends(get_db)):",
        "    from app.models import Proyecto",
        "    obj = await db.get(Proyecto, UUID(project_id))",
        "    if not obj: raise HTTPException(404)",
        "    for k, v in payload.items():",
        "        if hasattr(obj, k): setattr(obj, k, v)",
        "    await db.commit()",
        "    await db.refresh(obj)",
        "    return obj"
    ])

    # 2. GITHUB ROUTER: Fix Identity & Push Error
    w("backend/app/routers/github.py", [
        "import subprocess",
        "from uuid import UUID",
        "from fastapi import APIRouter, Depends",
        "from sqlalchemy.ext.asyncio import AsyncSession",
        "from app.database import get_db",
        "from app.config import get_settings",
        "from app.models import Proyecto",
        "router = APIRouter()",
        "settings = get_settings()",
        "async def get_cwd(project_id: str, db: AsyncSession):",
        "    p = await db.get(Proyecto, UUID(project_id))",
        "    path = settings.base_projects_dir / p.nombre_slug",
        "    path.mkdir(parents=True, exist_ok=True)",
        "    return str(path)",
        "@router.post('/{project_id}/status')",
        "async def git_status(project_id: str, db: AsyncSession = Depends(get_db)):",
        "    cwd = await get_cwd(project_id, db)",
        "    subprocess.run(['git', 'init'], cwd=cwd)",
        "    res = subprocess.run(['git', 'status'], cwd=cwd, capture_output=True, text=True)",
        "    return {'output': res.stdout or res.stderr}",
        "@router.post('/{project_id}/add')",
        "async def git_add(project_id: str, db: AsyncSession = Depends(get_db)):",
        "    cwd = await get_cwd(project_id, db)",
        "    res = subprocess.run(['git', 'add', '.'], cwd=cwd, capture_output=True, text=True)",
        "    return {'output': 'Archivos agregados al staging.\\n' + (res.stdout or res.stderr)}",
        "@router.post('/{project_id}/commit')",
        "async def git_commit(project_id: str, db: AsyncSession = Depends(get_db)):",
        "    cwd = await get_cwd(project_id, db)",
        "    subprocess.run(['git', 'config', 'user.email', 'bot@nodara.local'], cwd=cwd)",
        "    subprocess.run(['git', 'config', 'user.name', 'Nodara Bot'], cwd=cwd)",
        "    res = subprocess.run(['git', 'commit', '--allow-empty', '-m', 'Commit Nodara'], cwd=cwd, capture_output=True, text=True)",
        "    return {'output': res.stdout or res.stderr}",
        "@router.post('/{project_id}/push')",
        "async def git_push(project_id: str, db: AsyncSession = Depends(get_db)):",
        "    cwd = await get_cwd(project_id, db)",
        "    p = await db.get(Proyecto, UUID(project_id))",
        "    subprocess.run(['git', 'branch', '-M', 'main'], cwd=cwd)",
        "    if p.github_url and settings.github_personal_access_token:",
        "        tk = settings.github_personal_access_token",
        "        auth = p.github_url.replace('https://', f'https://{tk}@')",
        "        subprocess.run(['git', 'remote', 'set-url', 'origin', auth], cwd=cwd)",
        "        subprocess.run(['git', 'remote', 'add', 'origin', auth], cwd=cwd)",
        "        res = subprocess.run(['git', 'push', '-u', 'origin', 'main'], cwd=cwd, capture_output=True, text=True)",
        "        return {'output': res.stdout or res.stderr}",
        "    return {'output': 'Error: GitOps sin configurar.'}"
    ])

    # 3. ROUTERS VARIOS: Audit y Tools
    w("backend/app/routers/audit.py", [
        "from fastapi import APIRouter",
        "router = APIRouter()",
        "@router.get('/events')",
        "async def get_audit():",
        "    return [{'id': '1', 'timestamp': '2026-05-05T04:00:00Z', 'actor': 'Vitoto', 'action': 'Login', 'target': 'System', 'severity': 'info'}]"
    ])
    w("backend/app/routers/tools.py", [
        "from fastapi import APIRouter",
        "router = APIRouter()",
        "@router.get('')",
        "async def get_tools():",
        "    return [{'name': 'crear_archivos', 'description': 'Crea archivos.', 'requires_approval': True}]"
    ])

    # 4. FRONTEND CONFIGVIEW: FIX 422 Undefined
    w("frontend/features/config/ConfigView.tsx", [
        "\"use client\";",
        "import { useEffect, useState } from 'react';",
        "import { Badge } from '@/components/ui/Badge';",
        "import { Button } from '@/components/ui/Button';",
        "import { Card, CardTitle } from '@/components/ui/Card';",
        "import { SectionHeader } from '@/components/ui/SectionHeader';",
        "import { configRepository } from '@/services/repositories';",
        "export function ConfigView() {",
        "  const [config, setConfig] = useState<any>(null);",
        "  useEffect(() => { configRepository.list().then(items => setConfig(items[0] || null)); }, []);",
        "  async function toggleAutoApprove() {",
        "    const id = config?.id || 1;",
        "    await configRepository.patch(id, { auto_aprobar_ejecucion: !config?.auto_aprobar_ejecucion });",
        "    setConfig({...config, auto_aprobar_ejecucion: !config?.auto_aprobar_ejecucion});",
        "  }",
        "  return (",
        "    <div>",
        "      <SectionHeader title='Configuración operacional' description='Control BYOK.' />",
        "      <div className='grid gap-6 xl:grid-cols-[.8fr_1.2fr]'>",
        "        <Card>",
        "          <CardTitle eyebrow='Usuario' title={`ID ${config?.id ?? '1'}`} />",
        "          <div className='space-y-4'>",
        "            <div className='flex justify-between p-4 bg-brand-soft rounded-2xl'>",
        "              <span className='font-bold'>Auto aprobar ejecución</span>",
        "              <Badge tone={config?.auto_aprobar_ejecucion ? 'success' : 'warning'}>{config?.auto_aprobar_ejecucion ? 'ON' : 'OFF'}</Badge>",
        "            </div>",
        "            <Button onClick={toggleAutoApprove} className='w-full'>Alternar Auto Aprobación</Button>",
        "          </div>",
        "        </Card>",
        "        <Card>",
        "          <CardTitle eyebrow='BYOK' title='Estado de API Keys y saldos' />",
        "          <div className='grid gap-4 md:grid-cols-3'>",
        "            {[['OpenAI', config?.has_api_key_openai, config?.saldo_virtual_openai],",
        "              ['Anthropic', config?.has_api_key_anthropic, config?.saldo_virtual_anthropic],",
        "              ['Gemini', config?.has_api_key_gemini, config?.saldo_virtual_gemini]].map(([name, has, s]) => (",
        "              <div key={String(name)} className='rounded-3xl border bg-white p-5'>",
        "                <div className='text-lg font-black'>{String(name)}</div>",
        "                <Badge tone={has ? 'success' : 'danger'} className='mt-3'>{has ? 'Cargada' : 'Falta Key'}</Badge>",
        "              </div>",
        "            ))}",
        "            <div className='rounded-3xl border bg-white p-5 col-span-3'>",
        "              <div className='text-lg font-black'>GitHub GitOps</div>",
        "              <Badge tone={config?.has_api_key_github ? 'success' : 'danger'} className='mt-3'>",
        "                {config?.has_api_key_github ? 'Token Cargado en .env' : 'Falta GITHUB_PERSONAL_ACCESS_TOKEN'}",
        "              </Badge>",
        "            </div>",
        "          </div>",
        "        </Card>",
        "      </div>",
        "    </div>",
        "  );",
        "}"
    ])

    # 5. FRONTEND FUTURE TABLES: Agents per project, File Double Click
    w("frontend/features/future/FutureTables.tsx", [
        "\"use client\";",
        "import { useEffect, useState } from 'react';",
        "import { Badge } from '@/components/ui/Badge';",
        "import { Button } from '@/components/ui/Button';",
        "import { Card, CardTitle } from '@/components/ui/Card';",
        "import { SectionHeader } from '@/components/ui/SectionHeader';",
        "import { futureRepository, projectsRepository, githubRepository } from '@/services/repositories';",
        "import { formatDate } from '@/lib/format';",
        "function ProjectSelector({ projects, projectId, setProjectId }: any) {",
        "    if (projects.length === 0) return null;",
        "    return (",
        "        <div className='mb-6'>",
        "            <label className='mr-4 font-bold text-sm'>Seleccionar Proyecto:</label>",
        "            <select className='border border-brand-border bg-white p-2 rounded-xl text-sm' value={projectId} onChange={(e) => setProjectId(e.target.value)}>",
        "                {projects.map((p:any) => <option key={p.id} value={p.id}>{p.titulo}</option>)}",
        "            </select>",
        "        </div>",
        "    );",
        "}",
        "export function AgentsView() {",
        "  const [projects, setProjects] = useState<any[]>([]);",
        "  const [projectId, setProjectId] = useState<string>('');",
        "  const [project, setProject] = useState<any>(null);",
        "  const [edit, setEdit] = useState<string | null>(null);",
        "  const [temp, setTemp] = useState('');",
        "  useEffect(() => { projectsRepository.list().then(p => { setProjects(p); if(p.length > 0) setProjectId(p[0].id); }); }, []);",
        "  useEffect(() => { if(projectId) projectsRepository.get(projectId).then(setProject); }, [projectId]);",
        "  const save = async (key: string) => {",
        "    await projectsRepository.patch(projectId, { [key]: temp });",
        "    setProject({...project, [key]: temp}); setEdit(null);",
        "  };",
        "  return (",
        "    <div>",
        "      <SectionHeader title='Gestión de agentes' description='Roles por proyecto.' />",
        "      <ProjectSelector projects={projects} projectId={projectId} setProjectId={setProjectId} />",
        "      {project && (",
        "        <div className='grid gap-5 xl:grid-cols-3'>",
        "          {[['rol_gemini','Gemini'],['rol_chatgpt','ChatGPT'],['rol_claude','Claude']].map(([k, n]) => (",
        "            <Card key={k}><Badge tone='success'>{n}</Badge>",
        "            <div className='flex justify-between mt-3'><h3 className='font-black text-xl'>Rol</h3><button className='text-brand-cyan text-xs font-black uppercase' onClick={() => {setEdit(k); setTemp(project[k]);}}>Editar</button></div>",
        "            {edit === k ? <div className='mt-2'><textarea className='w-full text-xs p-2 border rounded' value={temp} onChange={e => setTemp(e.target.value)} /><Button onClick={() => save(k)}>Guardar</Button></div> : <p className='mt-2 text-sm text-brand-muted'>{project[k]}</p>}",
        "            </Card>",
        "          ))}",
        "        </div>",
        "      )}",
        "    </div>",
        "  );",
        "}",
        "function Tree({ nodes, depth = 0, onFileClick }: any) {",
        "  return (",
        "    <div className='space-y-1 mt-2'>",
        "      {nodes.map((node: any) => (",
        "        <div key={node.id} style={{ marginLeft: depth * 20 }}>",
        "          <div className={`px-2 py-1 text-sm rounded ${node.type === 'file' ? 'cursor-pointer hover:bg-brand-soft text-brand-cyan' : 'font-bold text-brand-navy'}`} onClick={() => node.type === 'file' && onFileClick(node.path)}>",
        "            {node.type === 'folder' ? '📁' : '📄'} {node.name}",
        "          </div>",
        "          {node.children && <Tree nodes={node.children} depth={depth + 1} onFileClick={onFileClick} />}",
        "        </div>",
        "      ))}",
        "    </div>",
        "  );",
        "}",
        "export function WorkspaceView() {",
        "  const [items, setItems] = useState<any[]>([]);",
        "  const [projects, setProjects] = useState<any[]>([]);",
        "  const [projectId, setProjectId] = useState<string>('');",
        "  const [fileContent, setFileContent] = useState<string>('');",
        "  useEffect(() => { projectsRepository.list().then(p => { setProjects(p); if(p.length > 0) setProjectId(p[0].id); }); }, []);",
        "  useEffect(() => { if (projectId) { futureRepository.workspace(projectId).then(setItems); setFileContent(''); } }, [projectId]);",
        "  const handleFileClick = async (path: string) => {",
        "      const res = await futureRepository.workspaceFile(projectId, path);",
        "      setFileContent(res?.content || 'Error leyendo el archivo.');",
        "  };",
        "  return (",
        "    <div>",
        "      <SectionHeader title='Workspace' description='Haz clic en un archivo para visualizarlo.' />",
        "      <ProjectSelector projects={projects} projectId={projectId} setProjectId={setProjectId} />",
        "      <div className='grid xl:grid-cols-[300px_1fr] gap-6'>",
        "        <Card>",
        "          <CardTitle title='Explorador' />",
        "          <Tree nodes={items} onFileClick={handleFileClick} />",
        "        </Card>",
        "        <Card>",
        "           <CardTitle title='Visualizador' />",
        "           <pre className='mt-4 p-4 bg-brand-deep text-brand-bright text-xs rounded-xl overflow-auto max-h-[600px]'>{fileContent || 'Selecciona un archivo del explorador.'}</pre>",
        "        </Card>",
        "      </div>",
        "    </div>",
        "  );",
        "}",
        "export function GithubView() {",
        "  const [projects, setProjects] = useState<any[]>([]);",
        "  const [projectId, setProjectId] = useState<string>('');",
        "  const [output, setOutput] = useState<string>('');",
        "  useEffect(() => { projectsRepository.list().then(p => { setProjects(p); if(p.length > 0) setProjectId(p[0].id); }); }, []);",
        "  const runCmd = async (action: 'status' | 'add' | 'commit' | 'push') => {",
        "      setOutput('Ejecutando...');",
        "      try {",
        "          const res = await githubRepository[action](projectId);",
        "          setOutput(res?.output || 'Ejecutado con éxito.');",
        "      } catch (e) { setOutput('Error.'); }",
        "  };",
        "  return (",
        "    <div>",
        "      <SectionHeader title='GitOps' description='Control de versiones.' />",
        "      <ProjectSelector projects={projects} projectId={projectId} setProjectId={setProjectId} />",
        "      <Card>",
        "        <div className='flex gap-2 mb-4'>",
        "            <Button variant='secondary' onClick={() => runCmd('status')}>Git Status</Button>",
        "            <Button variant='secondary' onClick={() => runCmd('add')}>Git Add .</Button>",
        "            <Button variant='secondary' onClick={() => runCmd('commit')}>Git Commit</Button>",
        "            <Button onClick={() => runCmd('push')}>Git Push</Button>",
        "        </div>",
        "        <pre className='bg-brand-deep text-brand-bright p-4 rounded-xl text-sm whitespace-pre-wrap'>{output}</pre>",
        "      </Card>",
        "    </div>",
        "  );",
        "}",
        "export function MetricsView() {",
        "  const [items, setItems] = useState<any[]>([]);",
        "  useEffect(() => { futureRepository.metrics().then(setItems); }, []);",
        "  return (",
        "    <div>",
        "      <SectionHeader title='Métricas' description='Dashboard.' />",
        "      <div className='grid gap-5 md:grid-cols-3'>",
        "        {items.map((m, i) => (",
        "        <Card key={i}>",
        "            <p className='text-sm font-bold text-brand-muted'>{m.label}</p>",
        "            <p className='mt-3 text-3xl font-black'>{m.value}</p>",
        "            <Badge tone={m.tone} className='mt-4'>{m.trend}</Badge>",
        "        </Card>",
        "        ))}",
        "      </div>",
        "    </div>",
        "  );",
        "}",
        "export function AuditView() {",
        "  const [items, setItems] = useState<any[]>([]);",
        "  useEffect(() => { futureRepository.audit().then(setItems); }, []);",
        "  return (",
        "    <div><SectionHeader title='Auditoría' description='Logs de sistema' />",
        "      <div className='space-y-4'>",
        "        {items.map((a:any) => (",
        "        <Card key={a.id}><Badge tone={a.severity}>{a.severity}</Badge>",
        "            <h3 className='mt-3 font-black'>{a.action}</h3>",
        "            <p className='mt-1 text-sm text-brand-muted'>{a.actor} · {a.target}</p>",
        "        </Card>",
        "        ))}",
        "      </div>",
        "    </div>",
        "  );",
        "}",
        "export function ToolsView() {",
        "  const [items, setItems] = useState<any[]>([]);",
        "  useEffect(() => { futureRepository.tools().then(setItems); }, []);",
        "  return (",
        "    <div><SectionHeader title='Catálogo Tools' description='Lectura libre vs escritura con HIL.' />",
        "      <div className='grid gap-5 md:grid-cols-2'>",
        "        {items.map((t:any) => (",
        "        <Card key={t.name}><Badge tone={t.requires_approval ? 'warning' : 'success'}>{t.requires_approval ? 'Requiere HIL' : 'Libre'}</Badge>",
        "            <h3 className='mt-3 text-lg font-black'>{t.name}</h3>",
        "            <p className='mt-2 text-sm text-brand-muted'>{t.description}</p>",
        "        </Card>",
        "        ))}",
        "      </div>",
        "    </div>",
        "  );",
        "}",
        "export function MessagesView() {",
        "  const [items, setItems] = useState<any[]>([]);",
        "  const [projects, setProjects] = useState<any[]>([]);",
        "  const [projectId, setProjectId] = useState<string>('');",
        "  useEffect(() => { projectsRepository.list().then(p => { setProjects(p); if(p.length > 0) setProjectId(p[0].id); }); }, []);",
        "  useEffect(() => { if(projectId) futureRepository.messages(projectId).then(setItems); }, [projectId]);",
        "  return (",
        "    <div><SectionHeader title='Mensajes' description='Historial por proyecto.' />",
        "      <ProjectSelector projects={projects} projectId={projectId} setProjectId={setProjectId} />",
        "      <div className='space-y-4'>",
        "        {items.map((m:any) => (",
        "        <Card key={m.id}><Badge tone={m.remitente === 'user' ? 'info' : 'success'}>{m.remitente}</Badge>",
        "            <p className='mt-3 text-sm text-brand-navy whitespace-pre-wrap'>{m.contenido}</p>",
        "        </Card>",
        "        ))}",
        "      </div>",
        "    </div>",
        "  );",
        "}"
    ])

    print("\n✅ Script finalizado correctamente.")

if __name__ == "__main__":
    deploy()