import os

def w(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"✅ Reconstruido: {path}")

def deploy():
    print("🚀 INICIANDO MEGA-PARCHE ENTERPRISE (SIN ERRORES DE SINTAXIS)...")

    # 1. GITHUB ROUTER (Fix Author Identity & Push Destination)
    w("backend/app/routers/github.py", [
        "import subprocess",
        "from uuid import UUID",
        "from fastapi import APIRouter, Depends",
        "from sqlalchemy.ext.asyncio import AsyncSession",
        "from app.database import get_db",
        "from app.config import get_settings",
        "from app.models import Proyecto",
        "router = APIRouter()",
        "settings = get_settings()",
        "async def get_cwd(project_id: str, db: AsyncSession):",
        "    p = await db.get(Proyecto, UUID(project_id))",
        "    path = settings.base_projects_dir / p.nombre_slug",
        "    path.mkdir(parents=True, exist_ok=True)",
        "    return str(path)",
        "@router.post('/{project_id}/status')",
        "async def git_status(project_id: str, db: AsyncSession = Depends(get_db)):",
        "    cwd = await get_cwd(project_id, db)",
        "    subprocess.run(['git', 'init'], cwd=cwd)",
        "    res = subprocess.run(['git', 'status'], cwd=cwd, capture_output=True, text=True)",
        "    return {'output': res.stdout or res.stderr}",
        "@router.post('/{project_id}/add')",
        "async def git_add(project_id: str, db: AsyncSession = Depends(get_db)):",
        "    cwd = await get_cwd(project_id, db)",
        "    res = subprocess.run(['git', 'add', '.'], cwd=cwd, capture_output=True, text=True)",
        "    return {'output': 'Archivos en staging.\\n' + (res.stdout or res.stderr)}",
        "@router.post('/{project_id}/commit')",
        "async def git_commit(project_id: str, db: AsyncSession = Depends(get_db)):",
        "    cwd = await get_cwd(project_id, db)",
        "    subprocess.run(['git', 'config', 'user.email', 'bot@nodara'], cwd=cwd)",
        "    subprocess.run(['git', 'config', 'user.name', 'NodaraBot'], cwd=cwd)",
        "    cmd = ['git', 'commit', '-m', 'Actualizacion Nodara']",
        "    res = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)",
        "    return {'output': res.stdout or res.stderr}",
        "@router.post('/{project_id}/push')",
        "async def git_push(project_id: str, db: AsyncSession = Depends(get_db)):",
        "    cwd = await get_cwd(project_id, db)",
        "    p = await db.get(Proyecto, UUID(project_id))",
        "    if p.github_url and settings.github_personal_access_token:",
        "        tk = settings.github_personal_access_token",
        "        auth = p.github_url.replace('https://', f'https://{tk}@')",
        "        subprocess.run(['git', 'remote', 'set-url', 'origin', auth], cwd=cwd)",
        "        cmd = ['git', 'push', '-u', 'origin', 'main']",
        "        res = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)",
        "        return {'output': res.stdout or res.stderr}",
        "    return {'output': 'Error: GitOps sin configurar.'}"
    ])

    # 2. CONFIG ROUTER (Exponer API Keys de .env)
    w("backend/app/routers/config.py", [
        "from fastapi import APIRouter, Depends",
        "from sqlalchemy import select",
        "from sqlalchemy.ext.asyncio import AsyncSession",
        "from app.database import get_db",
        "from app.config import get_settings",
        "router = APIRouter()",
        "settings = get_settings()",
        "@router.get('')",
        "async def get_config(db: AsyncSession = Depends(get_db)):",
        "    from app.models.governance import UsuarioConfig",
        "    res = await db.execute(select(UsuarioConfig))",
        "    cfg = res.scalars().first()",
        "    return [{",
        "        'id': cfg.id if cfg else 1,",
        "        'auto_aprobar_ejecucion': cfg.auto_aprobar_ejecucion if cfg else False,",
        "        'has_api_key_github': bool(settings.github_personal_access_token),",
        "        'has_api_key_openai': bool(settings.openai_api_key),",
        "        'has_api_key_anthropic': bool(settings.anthropic_api_key),",
        "        'has_api_key_gemini': bool(settings.gemini_api_key)",
        "    }]",
        "@router.patch('/{config_id}')",
        "async def update_config(config_id: int, payload: dict, db=Depends(get_db)):",
        "    from app.models.governance import UsuarioConfig",
        "    cfg = await db.get(UsuarioConfig, config_id)",
        "    if not cfg: cfg = UsuarioConfig(id=config_id); db.add(cfg)",
        "    for k, v in payload.items():",
        "        if hasattr(cfg, k): setattr(cfg, k, v)",
        "    await db.commit()",
        "    return {'status': 'ok'}"
    ])

    # 3. FRONTEND: REPOSITORIES (Reparando Errores de Metodos)
    w("frontend/services/repositories.ts", [
        "const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';",
        "async function fetchAPI(end: string, opts?: RequestInit) {",
        "  const res = await fetch(`${API}${end}`, {",
        "    ...opts, headers: { 'Content-Type': 'application/json', ...opts?.headers }",
        "  });",
        "  if(!res.ok) throw new Error(`HTTP ${res.status}`);",
        "  return await res.json();",
        "}",
        "function norm(d: any) { return Array.isArray(d) ? d : (d?.data || d?.items || []); }",
        "export const projectsRepository = {",
        "  list: async () => norm(await fetchAPI('/api/projects')),",
        "  get: async (id: string) => await fetchAPI(`/api/projects/${id}`),",
        "  create: async (p: any) => await fetchAPI('/api/projects', { method: 'POST', body: JSON.stringify(p) }),",
        "  patch: async (id: string, p: any) => await fetchAPI(`/api/projects/${id}`, { method: 'PATCH', body: JSON.stringify(p) })",
        "};",
        "export const futureRepository = {",
        "  messages: async (id: string) => norm(await fetchAPI(`/api/projects/${id}/messages`)),",
        "  workspace: async (id: string) => norm(await fetchAPI(`/api/projects/${id}/workspace/tree`)),",
        "  workspaceFile: async (id: string, path: string) => await fetchAPI(`/api/projects/${id}/workspace/file?file_path=${encodeURIComponent(path)}`),",
        "  readme: async (id: string) => await fetchAPI(`/api/projects/${id}/readme`),",
        "  updateReadme: async (id: string, c: string) => await fetchAPI(`/api/projects/${id}/readme`, { method: 'PATCH', body: JSON.stringify({ content: c }) }),",
        "  metrics: async () => norm(await fetchAPI('/api/metrics')),",
        "  agents: async () => norm(await fetchAPI('/api/agents')),",
        "  tools: async () => norm(await fetchAPI('/api/tools')),",
        "  audit: async () => norm(await fetchAPI('/api/audit/events'))",
        "};",
        "export const githubRepository = {",
        "  status: async (id: string) => await fetchAPI(`/api/github/${id}/status`, { method: 'POST' }),",
        "  add: async (id: string) => await fetchAPI(`/api/github/${id}/add`, { method: 'POST' }),",
        "  commit: async (id: string) => await fetchAPI(`/api/github/${id}/commit`, { method: 'POST' }),",
        "  push: async (id: string) => await fetchAPI(`/api/github/${id}/push`, { method: 'POST' })",
        "};",
        "export const filesRepository = {",
        "  list: async (id: string) => norm(await fetchAPI(`/api/files/${id}`)),",
        "  upload: async (id: string, file: File) => {",
        "    const data = new FormData();",
        "    data.append('file', file);",
        "    const res = await fetch(`${API}/api/files/${id}/upload`, { method: 'POST', body: data });",
        "    return await res.json();",
        "  }",
        "};",
        "export const configRepository = {",
        "  list: async () => norm(await fetchAPI('/api/config')),",
        "  patch: async (id: number, p: any) => await fetchAPI(`/api/config/${id}`, { method: 'PATCH', body: JSON.stringify(p) })",
        "};",
        "export const approvalsRepository = {",
        "  listAll: async () => norm(await fetchAPI('/api/approvals')),",
        "  approve: async (id: number) => await fetchAPI(`/api/approvals/${id}/approve`, { method: 'POST' }),",
        "  reject: async (id: number) => await fetchAPI(`/api/approvals/${id}/reject`, { method: 'POST' })",
        "};"
    ])

    # 4. FRONTEND: CHAT (Pegar imágenes del portapapeles)
    w("frontend/features/chat/MultiAgentChat.tsx", [
        "\"use client\";",
        "import { useEffect, useRef, useState } from 'react';",
        "import { Badge } from '@/components/ui/Badge';",
        "import { Button } from '@/components/ui/Button';",
        "import { Card, CardTitle } from '@/components/ui/Card';",
        "import { WS_BASE_URL } from '@/lib/env';",
        "import { filesRepository } from '@/services/repositories';",
        "export function MultiAgentChat({ projectId }: { projectId: string }) {",
        "  const [input, setInput] = useState('');",
        "  const [events, setEvents] = useState<any[]>([]);",
        "  const [status, setStatus] = useState('closed');",
        "  const wsRef = useRef<WebSocket | null>(null);",
        "  useEffect(() => {",
        "    const wsUrl = `${WS_BASE_URL}/ws/chat/${projectId}?usuario_config_id=1`;",
        "    const socket = new WebSocket(wsUrl);",
        "    wsRef.current = socket;",
        "    socket.onopen = () => setStatus('open');",
        "    socket.onclose = () => setStatus('closed');",
        "    socket.onmessage = (event) => {",
        "      try {",
        "        const raw = JSON.parse(event.data);",
        "        setEvents(prev => [...prev, { type: raw.event, agent: raw.data?.agent, message: raw.data?.message }]);",
        "      } catch {}",
        "    };",
        "    return () => socket.close();",
        "  }, [projectId]);",
        "  function send() {",
        "    if (!input.trim() || !wsRef.current) return;",
        "    wsRef.current.send(JSON.stringify({ message: input, correlation_id: crypto.randomUUID() }));",
        "    setInput('');",
        "  }",
        "  const uploadFile = async (file: File) => {",
        "    try {",
        "      await filesRepository.upload(projectId, file);",
        "      setInput(`[Archivo Subido: ${file.name}] Por favor analízalo.`);",
        "    } catch(err) { console.error('Upload Error', err); }",
        "  };",
        "  const handlePaste = (e: React.ClipboardEvent) => {",
        "    const items = e.clipboardData.items;",
        "    for (let i = 0; i < items.length; i++) {",
        "      if (items[i].type.indexOf('image') !== -1) {",
        "        const file = items[i].getAsFile();",
        "        if (file) uploadFile(file);",
        "      }",
        "    }",
        "  };",
        "  return (",
        "    <div className='grid gap-6 xl:grid-cols-[1fr_300px]'>",
        "      <Card className='min-h-[600px] flex flex-col'>",
        "        <CardTitle eyebrow='Conversación' title='Sala de orquestación' action={<Badge>{status}</Badge>} />",
        "        <div className='flex-1 overflow-y-auto bg-brand-soft rounded-2xl p-4 mt-4 space-y-4'>",
        "          {events.map((e, i) => (",
        "            <div key={i} className='bg-white p-3 rounded-xl shadow-sm'>",
        "              <span className='font-bold text-xs text-brand-cyan uppercase'>{e.type}</span>",
        "              {e.agent && <span className='ml-2 text-xs font-bold text-brand-navy'>[{e.agent}]</span>}",
        "              <p className='mt-2 text-sm whitespace-pre-wrap'>{e.message}</p>",
        "            </div>",
        "          ))}",
        "        </div>",
        "        <div className='mt-4 flex gap-2 items-center'>",
        "          <label className='cursor-pointer bg-brand-soft px-4 py-3 rounded-2xl border text-sm font-bold hover:bg-brand-border transition'>",
        "            📎 Subir",
        "            <input type='file' className='hidden' onChange={e => e.target.files?.[0] && uploadFile(e.target.files[0])} />",
        "          </label>",
        "          <input className='flex-1 rounded-2xl border px-4 py-3' placeholder='gemini: escribe o Pega (Ctrl+V) una imagen...' value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && send()} onPaste={handlePaste} />",
        "          <Button onClick={send}>Enviar</Button>",
        "        </div>",
        "      </Card>",
        "    </div>",
        "  );",
        "}"
    ])

    print("\n✅ Script finalizado sin errores de truncamiento de terminal.")
    print("👉 Ejecuta ahora: docker compose restart backend frontend")

if __name__ == "__main__":
    deploy()